Search.appendIndex(
    [
                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Controllers\\HealthcheckCronTaskController",
            "name": "HealthcheckCronTaskController",
            "summary": "Class\u0020\\Firesphere\\HealthcheckJobs\\Controllers\\HealthcheckCronTaskController",
            "url": "classes/Firesphere-HealthcheckJobs-Controllers-HealthcheckCronTaskController.html"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Controllers\\HealthcheckCronTaskController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Controllers-HealthcheckCronTaskController.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Controllers\\HealthcheckCronTaskController\u003A\u003ArunTask\u0028\u0029",
            "name": "runTask",
            "summary": "Checks\u0020and\u0020runs\u0020a\u0020single\u0020CronTask",
            "url": "classes/Firesphere-HealthcheckJobs-Controllers-HealthcheckCronTaskController.html#method_runTask"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Controllers\\HealthcheckCronTaskController\u003A\u003A\u0024healthService",
            "name": "healthService",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Controllers-HealthcheckCronTaskController.html#property_healthService"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckQueuedJobService",
            "name": "HealthcheckQueuedJobService",
            "summary": "Class\u0020\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckQueuedJobService",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckQueuedJobService.html"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckQueuedJobService\u003A\u003ArunJob\u0028\u0029",
            "name": "runJob",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckQueuedJobService.html#method_runJob"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckQueuedJobService\u003A\u003A\u0024healthService",
            "name": "healthService",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckQueuedJobService.html#property_healthService"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService",
            "name": "HealthcheckService",
            "summary": "Class\u0020\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003AgetCheck\u0028\u0029",
            "name": "getCheck",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method_getCheck"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method_init"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method_start"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003Asuccess\u0028\u0029",
            "name": "success",
            "summary": "Stub\u0020for\u0020success",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method_success"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003Aping\u0028\u0029",
            "name": "ping",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method_ping"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003Afail\u0028\u0029",
            "name": "fail",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method_fail"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003AgetTask\u0028\u0029",
            "name": "getTask",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method_getTask"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003AsetTask\u0028\u0029",
            "name": "setTask",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#method_setTask"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003A\u0024endpoint",
            "name": "endpoint",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#property_endpoint"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003A\u0024api_key",
            "name": "api_key",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#property_api_key"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003A\u0024api_version",
            "name": "api_version",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#property_api_version"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003A\u0024versions",
            "name": "versions",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#property_versions"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003A\u0024task",
            "name": "task",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#property_task"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003A\u0024pingUrl",
            "name": "pingUrl",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#property_pingUrl"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services\\HealthcheckService\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/Firesphere-HealthcheckJobs-Services-HealthcheckService.html#property_client"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/firesphere-healthcheckjobs-controllers.html"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs",
            "name": "HealthcheckJobs",
            "summary": "",
            "url": "namespaces/firesphere-healthcheckjobs.html"
        },                {
            "fqsen": "\\Firesphere",
            "name": "Firesphere",
            "summary": "",
            "url": "namespaces/firesphere.html"
        },                {
            "fqsen": "\\Firesphere\\HealthcheckJobs\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/firesphere-healthcheckjobs-services.html"
        }            ]
);
