Search.appendIndex(
    [
                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserAuthenticator",
            "name": "AnonymousUserAuthenticator",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserAuthenticator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserAuthenticator\u003A\u003AsupportedServices\u0028\u0029",
            "name": "supportedServices",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserAuthenticator.html#method_supportedServices"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserAuthenticator\u003A\u003AauthenticateMember\u0028\u0029",
            "name": "authenticateMember",
            "summary": "Attempt\u0020to\u0020find\u0020and\u0020authenticate\u0020member\u0020if\u0020possible\u0020from\u0020the\u0020given\u0020data",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserAuthenticator.html#method_authenticateMember"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserAuthenticator\u003A\u003AcheckPassword\u0028\u0029",
            "name": "checkPassword",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserAuthenticator.html#method_checkPassword"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserAuthenticator\u003A\u003A\u0024anonymous_username",
            "name": "anonymous_username",
            "summary": "Anonymous\u0020username",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserAuthenticator.html#property_anonymous_username"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserFactory",
            "name": "AnonymousUserFactory",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserFactory.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Creates\u0020a\u0020new\u0020service\u0020instance.",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserFactory.html#method_create"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\AnonymousUserFactory\u003A\u003A\u0024anonymous_fields",
            "name": "anonymous_fields",
            "summary": "Default\u0020field\u0020values\u0020to\u0020assign\u0020to\u0020anonymous\u0020user",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-AnonymousUserFactory.html#property_anonymous_fields"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticationHandler",
            "name": "JWTAuthenticationHandler",
            "summary": "Class\u0020JWTAuthenticationHandler",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticationHandler.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticationHandler\u003A\u003AauthenticateRequest\u0028\u0029",
            "name": "authenticateRequest",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticationHandler.html#method_authenticateRequest"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticationHandler\u003A\u003AlogIn\u0028\u0029",
            "name": "logIn",
            "summary": "Authenticate\u0020on\u0020every\u0020run,\u0020based\u0020on\u0020the\u0020header,\u0020not\u0020relying\u0020on\u0020sessions\u0020or\u0020cookies\nJSON\u0020Web\u0020Tokens\u0020are\u0020stateless",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticationHandler.html#method_logIn"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticationHandler\u003A\u003AlogOut\u0028\u0029",
            "name": "logOut",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticationHandler.html#method_logOut"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator",
            "name": "JWTAuthenticator",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AgetKeyType\u0028\u0029",
            "name": "getKeyType",
            "summary": "Keys\u0020are\u0020one\u0020of\u003A\n\u0020\u0020\u002D\u0020public\u0020\/\u0020private\u0020RSA\u0020pair\u0020files\n\u0020\u0020\u002D\u0020public\u0020\/\u0020private\u0020RSA\u0020pair\u0020files,\u0020password\u0020protected\u0020private\u0020key\n\u0020\u0020\u002D\u0020private\u0020HMAC\u0020string",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_getKeyType"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AgetSigner\u0028\u0029",
            "name": "getSigner",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_getSigner"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AgetPrivateKey\u0028\u0029",
            "name": "getPrivateKey",
            "summary": "Get\u0020private\u0020key\u0020used\u0020to\u0020generate\u0020JWT\u0020tokens",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_getPrivateKey"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AgetPublicKey\u0028\u0029",
            "name": "getPublicKey",
            "summary": "Get\u0020public\u0020key\u0020used\u0020to\u0020validate\u0020JWT\u0020tokens",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_getPublicKey"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AmakeKey\u0028\u0029",
            "name": "makeKey",
            "summary": "Construct\u0020a\u0020new\u0020key\u0020from\u0020the\u0020named\u0020config\u0020variable",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_makeKey"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AsupportedServices\u0028\u0029",
            "name": "supportedServices",
            "summary": "JWT\u0020is\u0020stateless,\u0020therefore,\u0020we\u0020don\u0027t\u0020support\u0020anything\u0020but\u0020login",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_supportedServices"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AgenerateToken\u0028\u0029",
            "name": "generateToken",
            "summary": "Generate\u0020a\u0020new\u0020JWT\u0020token\u0020for\u0020a\u0020given\u0020request,\u0020and\u0020optional\u0020\u0028if\u0020anonymous_allowed\u0029\u0020user",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_generateToken"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AvalidateToken\u0028\u0029",
            "name": "validateToken",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_validateToken"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AparseToken\u0028\u0029",
            "name": "parseToken",
            "summary": "Parse\u0020a\u0020string\u0020into\u0020a\u0020token",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_parseToken"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AvalidateParsedToken\u0028\u0029",
            "name": "validateParsedToken",
            "summary": "Determine\u0020if\u0020the\u0020given\u0020token\u0020is\u0020current,\u0020given\u0020the\u0020context\u0020of\u0020the\u0020current\u0020request",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_validateParsedToken"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AcanTokenBeRenewed\u0028\u0029",
            "name": "canTokenBeRenewed",
            "summary": "Check\u0020if\u0020the\u0020given\u0020token\u0020can\u0020be\u0020renewed",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_canTokenBeRenewed"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AresolvePath\u0028\u0029",
            "name": "resolvePath",
            "summary": "Return\u0020an\u0020absolute\u0020path\u0020from\u0020a\u0020relative\u0020one\nIf\u0020the\u0020path\u0020doesn\u0027t\u0020exist,\u0020returns\u0020null",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_resolvePath"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AgetEnv\u0028\u0029",
            "name": "getEnv",
            "summary": "Get\u0020an\u0020environment\u0020value.\u0020If\u0020\u0024default\u0020is\u0020not\u0020set\u0020and\u0020the\u0020environment\u0020isn\u0027t\u0020set\u0020either\u0020this\u0020will\u0020error.",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#method_getEnv"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AJWT_SIGNER_KEY",
            "name": "JWT_SIGNER_KEY",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#constant_JWT_SIGNER_KEY"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AJWT_KEY_PASSWORD",
            "name": "JWT_KEY_PASSWORD",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#constant_JWT_KEY_PASSWORD"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AJWT_PUBLIC_KEY",
            "name": "JWT_PUBLIC_KEY",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#constant_JWT_PUBLIC_KEY"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003ARSA",
            "name": "RSA",
            "summary": "Key\u0020is\u0020RSA\u0020public\/private\u0020pair",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#constant_RSA"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003ARSA_PASSWORD",
            "name": "RSA_PASSWORD",
            "summary": "Key\u0020is\u0020RSA\u0020public\/private\u0020pair,\u0020with\u0020password\u0020enabled",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#constant_RSA_PASSWORD"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003AHMAC",
            "name": "HMAC",
            "summary": "Key\u0020is\u0020HMAC\u0020string",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#constant_HMAC"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003A\u0024anonymous_allowed",
            "name": "anonymous_allowed",
            "summary": "Set\u0020to\u0020true\u0020to\u0020allow\u0020anonymous\u0020JWT\u0020tokens\u0020\u0028no\u0020member\u0020record\u0020\/\u0020email\u0020\/\u0020password\u0029",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#property_anonymous_allowed"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003A\u0024nbf_time",
            "name": "nbf_time",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#property_nbf_time"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003A\u0024nbf_expiration",
            "name": "nbf_expiration",
            "summary": "Expires\u0020after\u00201\u0020hour",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#property_nbf_expiration"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication\\JWTAuthenticator\u003A\u003A\u0024nbf_refresh_expiration",
            "name": "nbf_refresh_expiration",
            "summary": "Token\u0020can\u0020be\u0020refreshed\u0020within\u00207\u0020days",
            "url": "classes/Firesphere-GraphQLJWT-Authentication-JWTAuthenticator.html#property_nbf_refresh_expiration"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Extensions\\MemberExtension",
            "name": "MemberExtension",
            "summary": "Class\u0020MemberExtension\nAdd\u0020a\u0020unique\u0020token\u0020to\u0020the\u0020Member\u0020for\u0020extra\u0020validation",
            "url": "classes/Firesphere-GraphQLJWT-Extensions-MemberExtension.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Extensions\\MemberExtension\u003A\u003AupdateCMSFields\u0028\u0029",
            "name": "updateCMSFields",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Extensions-MemberExtension.html#method_updateCMSFields"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Extensions\\MemberExtension\u003A\u003AgetJWTData\u0028\u0029",
            "name": "getJWTData",
            "summary": "Option\u0020to\u0020add\u0020data\u0020to\u0020the\u0020JWT\u0020Subject",
            "url": "classes/Firesphere-GraphQLJWT-Extensions-MemberExtension.html#method_getJWTData"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Extensions\\MemberExtension\u003A\u003AdestroyAuthTokens\u0028\u0029",
            "name": "destroyAuthTokens",
            "summary": "Destroy\u0020all\u0020JWT\u0020tokens",
            "url": "classes/Firesphere-GraphQLJWT-Extensions-MemberExtension.html#method_destroyAuthTokens"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Extensions\\MemberExtension\u003A\u003A\u0024jwt_subject_fields",
            "name": "jwt_subject_fields",
            "summary": "List\u0020of\u0020names\u0020of\u0020extra\u0020subject\u0020fields\u0020to\u0020add\u0020to\u0020JWT\u0020token",
            "url": "classes/Firesphere-GraphQLJWT-Extensions-MemberExtension.html#property_jwt_subject_fields"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Extensions\\MemberExtension\u003A\u003A\u0024has_many",
            "name": "has_many",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Extensions-MemberExtension.html#property_has_many"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\HeaderExtractor",
            "name": "HeaderExtractor",
            "summary": "Parent\u0020class\u0020can\u0020detect\u0020JWT\u0020tokens\u0020in\u0020a\u0020request",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-HeaderExtractor.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\HeaderExtractor\u003A\u003AgetAuthorizationHeader\u0028\u0029",
            "name": "getAuthorizationHeader",
            "summary": "Get\u0020JWT\u0020from\u0020request,\u0020or\u0020null\u0020if\u0020not\u0020present",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-HeaderExtractor.html#method_getAuthorizationHeader"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\MemberTokenGenerator",
            "name": "MemberTokenGenerator",
            "summary": "Generates\u0020\/\u0020Validates\u0020a\u0020MemberTokenType\u0020for\u0020graphql\u0020responses",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-MemberTokenGenerator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\MemberTokenGenerator\u003A\u003AgetErrorMessage\u0028\u0029",
            "name": "getErrorMessage",
            "summary": "Humanise\u0020error\u0020message\u0020based\u0020on\u0020status\u0020code",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-MemberTokenGenerator.html#method_getErrorMessage"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\MemberTokenGenerator\u003A\u003AgenerateResponse\u0028\u0029",
            "name": "generateResponse",
            "summary": "Generate\u0020MemberToken\u0020response",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-MemberTokenGenerator.html#method_generateResponse"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\RequiresAuthenticator",
            "name": "RequiresAuthenticator",
            "summary": "Parent\u0020class\u0020requires\u0020a\u0020JWTAuthenticator\u0020instance\u0020to\u0020be\u0020injected",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-RequiresAuthenticator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\RequiresAuthenticator\u003A\u003AgetJWTAuthenticator\u0028\u0029",
            "name": "getJWTAuthenticator",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-RequiresAuthenticator.html#method_getJWTAuthenticator"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\RequiresAuthenticator\u003A\u003AsetJWTAuthenticator\u0028\u0029",
            "name": "setJWTAuthenticator",
            "summary": "Inject\u0020authenticator\u0020this\u0020mutation\u0020should\u0020use",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-RequiresAuthenticator.html#method_setJWTAuthenticator"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers\\RequiresAuthenticator\u003A\u003A\u0024jwtAuthenticator",
            "name": "jwtAuthenticator",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Helpers-RequiresAuthenticator.html#property_jwtAuthenticator"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Model\\JWTRecord",
            "name": "JWTRecord",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Model-JWTRecord.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Model\\JWTRecord\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Model-JWTRecord.html#property_table_name"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Model\\JWTRecord\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Model-JWTRecord.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Model\\JWTRecord\u003A\u003A\u0024has_one",
            "name": "has_one",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Model-JWTRecord.html#property_has_one"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Model\\JWTRecord\u003A\u003A\u0024indexes",
            "name": "indexes",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Model-JWTRecord.html#property_indexes"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator",
            "name": "CreateTokenMutationCreator",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003AgetCustomAuthenticators\u0028\u0029",
            "name": "getCustomAuthenticators",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#method_getCustomAuthenticators"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003AsetCustomAuthenticators\u0028\u0029",
            "name": "setCustomAuthenticators",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#method_setCustomAuthenticators"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003Aattributes\u0028\u0029",
            "name": "attributes",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#method_attributes"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#method_type"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003Aargs\u0028\u0029",
            "name": "args",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#method_args"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#method_resolve"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003AgetAuthenticatedMember\u0028\u0029",
            "name": "getAuthenticatedMember",
            "summary": "Get\u0020an\u0020authenticated\u0020member\u0020from\u0020the\u0020given\u0020request",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#method_getAuthenticatedMember"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003AgetLoginAuthenticators\u0028\u0029",
            "name": "getLoginAuthenticators",
            "summary": "Get\u0020any\u0020authenticator\u0020we\u0020should\u0020use\u0020for\u0020logging\u0020in\u0020users",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#method_getLoginAuthenticators"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\CreateTokenMutationCreator\u003A\u003A\u0024customAuthenticators",
            "name": "customAuthenticators",
            "summary": "Extra\u0020authenticators\u0020to\u0020use\u0020for\u0020logging\u0020in\u0020with\u0020username\u0020\/\u0020password",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-CreateTokenMutationCreator.html#property_customAuthenticators"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\RefreshTokenMutationCreator",
            "name": "RefreshTokenMutationCreator",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-RefreshTokenMutationCreator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\RefreshTokenMutationCreator\u003A\u003Aattributes\u0028\u0029",
            "name": "attributes",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-RefreshTokenMutationCreator.html#method_attributes"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\RefreshTokenMutationCreator\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-RefreshTokenMutationCreator.html#method_type"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations\\RefreshTokenMutationCreator\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Mutations-RefreshTokenMutationCreator.html#method_resolve"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Queries\\ValidateTokenQueryCreator",
            "name": "ValidateTokenQueryCreator",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Queries-ValidateTokenQueryCreator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Queries\\ValidateTokenQueryCreator\u003A\u003Aattributes\u0028\u0029",
            "name": "attributes",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Queries-ValidateTokenQueryCreator.html#method_attributes"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Queries\\ValidateTokenQueryCreator\u003A\u003Aargs\u0028\u0029",
            "name": "args",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Queries-ValidateTokenQueryCreator.html#method_args"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Queries\\ValidateTokenQueryCreator\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Queries-ValidateTokenQueryCreator.html#method_type"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Queries\\ValidateTokenQueryCreator\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Queries-ValidateTokenQueryCreator.html#method_resolve"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\MemberTokenTypeCreator",
            "name": "MemberTokenTypeCreator",
            "summary": "Represents\u0020a\u0020member\u0020\/\u0020token\u0020pair",
            "url": "classes/Firesphere-GraphQLJWT-Types-MemberTokenTypeCreator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\MemberTokenTypeCreator\u003A\u003Aattributes\u0028\u0029",
            "name": "attributes",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Types-MemberTokenTypeCreator.html#method_attributes"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\MemberTokenTypeCreator\u003A\u003Afields\u0028\u0029",
            "name": "fields",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Types-MemberTokenTypeCreator.html#method_fields"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\MemberTypeCreator",
            "name": "MemberTypeCreator",
            "summary": "A\u0020logged\u0020in\u0020member",
            "url": "classes/Firesphere-GraphQLJWT-Types-MemberTypeCreator.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\MemberTypeCreator\u003A\u003Aattributes\u0028\u0029",
            "name": "attributes",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Types-MemberTypeCreator.html#method_attributes"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\MemberTypeCreator\u003A\u003Afields\u0028\u0029",
            "name": "fields",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Types-MemberTypeCreator.html#method_fields"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\TokenStatusEnum",
            "name": "TokenStatusEnum",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Types-TokenStatusEnum.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\TokenStatusEnum\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-GraphQLJWT-Types-TokenStatusEnum.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\TokenStatusEnum\u003A\u003Ainstance\u0028\u0029",
            "name": "instance",
            "summary": "Safely\u0020create\u0020a\u0020single\u0020type\u0020creator\u0020only",
            "url": "classes/Firesphere-GraphQLJWT-Types-TokenStatusEnum.html#method_instance"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\TokenStatusEnum\u003A\u003ASTATUS_OK",
            "name": "STATUS_OK",
            "summary": "Valid\u0020token",
            "url": "classes/Firesphere-GraphQLJWT-Types-TokenStatusEnum.html#constant_STATUS_OK"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\TokenStatusEnum\u003A\u003ASTATUS_INVALID",
            "name": "STATUS_INVALID",
            "summary": "Not\u0020a\u0020valid\u0020token",
            "url": "classes/Firesphere-GraphQLJWT-Types-TokenStatusEnum.html#constant_STATUS_INVALID"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\TokenStatusEnum\u003A\u003ASTATUS_EXPIRED",
            "name": "STATUS_EXPIRED",
            "summary": "Expired\u0020but\u0020can\u0020be\u0020renewed",
            "url": "classes/Firesphere-GraphQLJWT-Types-TokenStatusEnum.html#constant_STATUS_EXPIRED"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\TokenStatusEnum\u003A\u003ASTATUS_DEAD",
            "name": "STATUS_DEAD",
            "summary": "Expired\u0020and\u0020cannot\u0020be\u0020renewed",
            "url": "classes/Firesphere-GraphQLJWT-Types-TokenStatusEnum.html#constant_STATUS_DEAD"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types\\TokenStatusEnum\u003A\u003ASTATUS_BAD_LOGIN",
            "name": "STATUS_BAD_LOGIN",
            "summary": "Provided\u0020user\u0020\/\u0020password\u0020were\u0020incorrect",
            "url": "classes/Firesphere-GraphQLJWT-Types-TokenStatusEnum.html#constant_STATUS_BAD_LOGIN"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Authentication",
            "name": "Authentication",
            "summary": "",
            "url": "namespaces/firesphere-graphqljwt-authentication.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT",
            "name": "GraphQLJWT",
            "summary": "",
            "url": "namespaces/firesphere-graphqljwt.html"
        },                {
            "fqsen": "\\Firesphere",
            "name": "Firesphere",
            "summary": "",
            "url": "namespaces/firesphere.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Extensions",
            "name": "Extensions",
            "summary": "",
            "url": "namespaces/firesphere-graphqljwt-extensions.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/firesphere-graphqljwt-helpers.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Model",
            "name": "Model",
            "summary": "",
            "url": "namespaces/firesphere-graphqljwt-model.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Mutations",
            "name": "Mutations",
            "summary": "",
            "url": "namespaces/firesphere-graphqljwt-mutations.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Queries",
            "name": "Queries",
            "summary": "",
            "url": "namespaces/firesphere-graphqljwt-queries.html"
        },                {
            "fqsen": "\\Firesphere\\GraphQLJWT\\Types",
            "name": "Types",
            "summary": "",
            "url": "namespaces/firesphere-graphqljwt-types.html"
        }            ]
);
