Search.appendIndex(
    [
                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\PageControllerExtension",
            "name": "PageControllerExtension",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-PageControllerExtension.html"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\PageControllerExtension\u003A\u003AonAfterInit\u0028\u0029",
            "name": "onAfterInit",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-PageControllerExtension.html#method_onAfterInit"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\PageControllerExtension\u003A\u003AAdblockWarning\u0028\u0029",
            "name": "AdblockWarning",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-PageControllerExtension.html#method_AdblockWarning"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\PageControllerExtension\u003A\u003AsetEnabled\u0028\u0029",
            "name": "setEnabled",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-PageControllerExtension.html#method_setEnabled"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\PageControllerExtension\u003A\u003A\u0024enabled",
            "name": "enabled",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-PageControllerExtension.html#property_enabled"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\PageControllerExtension\u003A\u003A\u0024adblockWarning",
            "name": "adblockWarning",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-PageControllerExtension.html#property_adblockWarning"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\SiteConfigExtension",
            "name": "SiteConfigExtension",
            "summary": "class\u0020Firesphere\\AdblockWarning\\Extensions\\SiteConfigExtension",
            "url": "classes/Firesphere-AdblockWarning-Extensions-SiteConfigExtension.html"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\SiteConfigExtension\u003A\u003AupdateCMSFields\u0028\u0029",
            "name": "updateCMSFields",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-SiteConfigExtension.html#method_updateCMSFields"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\SiteConfigExtension\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-SiteConfigExtension.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions\\SiteConfigExtension\u003A\u003A\u0024defaults",
            "name": "defaults",
            "summary": "",
            "url": "classes/Firesphere-AdblockWarning-Extensions-SiteConfigExtension.html#property_defaults"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning\\Extensions",
            "name": "Extensions",
            "summary": "",
            "url": "namespaces/firesphere-adblockwarning-extensions.html"
        },                {
            "fqsen": "\\Firesphere\\AdblockWarning",
            "name": "AdblockWarning",
            "summary": "",
            "url": "namespaces/firesphere-adblockwarning.html"
        },                {
            "fqsen": "\\Firesphere",
            "name": "Firesphere",
            "summary": "",
            "url": "namespaces/firesphere.html"
        }            ]
);
