Search.appendIndex(
    [
                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Admins\\LocationAdmin",
            "name": "LocationAdmin",
            "summary": "Class\u0020\\Firesphere\\Wedding\\Admins\\LocationAdmin",
            "url": "classes/Firesphere-OpenStreetmaps-Admins-LocationAdmin.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Admins\\LocationAdmin\u003A\u003A\u0024managed_models",
            "name": "managed_models",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Admins-LocationAdmin.html#property_managed_models"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Admins\\LocationAdmin\u003A\u003A\u0024menu_title",
            "name": "menu_title",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Admins-LocationAdmin.html#property_menu_title"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Admins\\LocationAdmin\u003A\u003A\u0024url_segment",
            "name": "url_segment",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Admins-LocationAdmin.html#property_url_segment"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Admins\\LocationAdmin\u003A\u003A\u0024menu_icon_class",
            "name": "menu_icon_class",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Admins-LocationAdmin.html#property_menu_icon_class"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\PageControllerExtension",
            "name": "PageControllerExtension",
            "summary": "Class\u0020\\Firesphere\\OpenStreetmaps\\Extensions\\PageControllerExtension",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-PageControllerExtension.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\PageControllerExtension\u003A\u003AonAfterInit\u0028\u0029",
            "name": "onAfterInit",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-PageControllerExtension.html#method_onAfterInit"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\PageControllerExtension\u003A\u003A\u0024db_to_js_map",
            "name": "db_to_js_map",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-PageControllerExtension.html#property_db_to_js_map"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\PageExtension",
            "name": "PageExtension",
            "summary": "Class\u0020\\Firesphere\\OpenStreetmaps\\Extensions\\PageExtension",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-PageExtension.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\PageExtension\u003A\u003AupdateCMSFields\u0028\u0029",
            "name": "updateCMSFields",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-PageExtension.html#method_updateCMSFields"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\PageExtension\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-PageExtension.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\SiteConfigExtension",
            "name": "SiteConfigExtension",
            "summary": "Class\u0020\\Firesphere\\OpenStreetmaps\\Extensions\\SiteConfigExtension",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-SiteConfigExtension.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\SiteConfigExtension\u003A\u003AupdateCMSFields\u0028\u0029",
            "name": "updateCMSFields",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-SiteConfigExtension.html#method_updateCMSFields"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\SiteConfigExtension\u003A\u003A\u0024map_styles",
            "name": "map_styles",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-SiteConfigExtension.html#property_map_styles"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\SiteConfigExtension\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-SiteConfigExtension.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions\\SiteConfigExtension\u003A\u003A\u0024defaults",
            "name": "defaults",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Extensions-SiteConfigExtension.html#property_defaults"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField",
            "name": "MapboxField",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField\u003A\u003AgetLocationObject\u0028\u0029",
            "name": "getLocationObject",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html#method_getLocationObject"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField\u003A\u003AsetLocationObject\u0028\u0029",
            "name": "setLocationObject",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html#method_setLocationObject"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField\u003A\u003AgetHiddenFields\u0028\u0029",
            "name": "getHiddenFields",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html#method_getHiddenFields"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField\u003A\u003AforTemplate\u0028\u0029",
            "name": "forTemplate",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html#method_forTemplate"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField\u003A\u003A\u0024locationObject",
            "name": "locationObject",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html#property_locationObject"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField\u003A\u003A\u0024accessToken",
            "name": "accessToken",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html#property_accessToken"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms\\MapboxField\u003A\u003A\u0024record_fields",
            "name": "record_fields",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Forms-MapboxField.html#property_record_fields"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\Location",
            "name": "Location",
            "summary": "Class\u0020\\Firesphere\\OpenStreetmaps\\Models\\Location",
            "url": "classes/Firesphere-OpenStreetmaps-Models-Location.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\Location\u003A\u003AgetCMSFields\u0028\u0029",
            "name": "getCMSFields",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-Location.html#method_getCMSFields"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\Location\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-Location.html#property_table_name"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\Location\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-Location.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\Location\u003A\u003A\u0024has_one",
            "name": "has_one",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-Location.html#property_has_one"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\Location\u003A\u003A\u0024has_many",
            "name": "has_many",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-Location.html#property_has_many"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\StaticImage",
            "name": "StaticImage",
            "summary": "Class\u0020\\Firesphere\\OpenStreetmaps\\Models\\StaticImage",
            "url": "classes/Firesphere-OpenStreetmaps-Models-StaticImage.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\StaticImage\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-StaticImage.html#property_table_name"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\StaticImage\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-StaticImage.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\StaticImage\u003A\u003A\u0024has_one",
            "name": "has_one",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-StaticImage.html#property_has_one"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models\\StaticImage\u003A\u003A\u0024owns",
            "name": "owns",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Models-StaticImage.html#property_owns"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Services\\OpenStreetmapService",
            "name": "OpenStreetmapService",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Services-OpenStreetmapService.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Services\\OpenStreetmapService\u003A\u003AgetStaticMapImage\u0028\u0029",
            "name": "getStaticMapImage",
            "summary": "Fetches\u0020a\u0020generated\u0020static\u0020image\u0020from\u0020Mapbox,\u0020and\u0020stores\u0020it\u0020locally\nto\u0020avoid\u0020potential\u0020slow\u0020responses\u0020or\u0020key\u0020exhaustion.",
            "url": "classes/Firesphere-OpenStreetmaps-Services-OpenStreetmapService.html#method_getStaticMapImage"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Services\\OpenStreetmapService\u003A\u003AaddLocations\u0028\u0029",
            "name": "addLocations",
            "summary": "Put\u0020the\u0020list\u0020of\u0020locations\u0020in\u0020to\u0020the\u0020\u003Chead\u003E\u0020element.",
            "url": "classes/Firesphere-OpenStreetmaps-Services-OpenStreetmapService.html#method_addLocations"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Services\\OpenStreetmapService\u003A\u003AgetMapLocation\u0028\u0029",
            "name": "getMapLocation",
            "summary": "",
            "url": "classes/Firesphere-OpenStreetmaps-Services-OpenStreetmapService.html#method_getMapLocation"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Services\\OpenStreetmapService\u003A\u003A\u0024mapbox_url",
            "name": "mapbox_url",
            "summary": "API\u0020endpoint\u0020for\u0020static\u0020maps\nFull\u0020URL\u0020Format\u003A\n\u005B\n\u0020https\n\u0020URI\n\u0020styles\n\u0020v1\n\u0020\u007B\u0040config\u0020self\u003A\u003Aconfig\u0028\u0029\u002D\u003Eget\u0028\u0027static\u0027\u0029\u005B\u0027style\u0027\u005D\u003B\n\u0020static\n\u0020latitude\n\u0020longitude\n\u0020\u007B\u0040config\u0020self\u003A\u003Aconfig\u0028\u0029\u002D\u003Eget\u0028\u0027static\u0027\u0029\u005B\u0027width\u0027\u005D\n\u0020\u007B\u0040config\u0020self\u003A\u003Aconfig\u0028\u0029\u002D\u003Eget\u0028\u0027static\u0027\u0029\u005B\u0027height\u0027\u005D\n\u005D\nget\u0020params\u003A\u0020Environment\u003A\u003AgetEnv\u0028\u0027MAPBOX_TOKEN\u0027\u0029\u003B",
            "url": "classes/Firesphere-OpenStreetmaps-Services-OpenStreetmapService.html#property_mapbox_url"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Admins",
            "name": "Admins",
            "summary": "",
            "url": "namespaces/firesphere-openstreetmaps-admins.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps",
            "name": "OpenStreetmaps",
            "summary": "",
            "url": "namespaces/firesphere-openstreetmaps.html"
        },                {
            "fqsen": "\\Firesphere",
            "name": "Firesphere",
            "summary": "",
            "url": "namespaces/firesphere.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Extensions",
            "name": "Extensions",
            "summary": "",
            "url": "namespaces/firesphere-openstreetmaps-extensions.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Forms",
            "name": "Forms",
            "summary": "",
            "url": "namespaces/firesphere-openstreetmaps-forms.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/firesphere-openstreetmaps-models.html"
        },                {
            "fqsen": "\\Firesphere\\OpenStreetmaps\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/firesphere-openstreetmaps-services.html"
        }            ]
);
