Search.appendIndex(
    [
                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\AutomaticMarkupID",
            "name": "AutomaticMarkupID",
            "summary": "Add\u0020sitetree\u0020type\u0020to\u0020link\u0020field",
            "url": "classes/gorriecoe-Link-Extensions-AutomaticMarkupID.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\AutomaticMarkupID\u003A\u003AupdateIDValue\u0028\u0029",
            "name": "updateIDValue",
            "summary": "Renders\u0020an\u0020HTML\u0020ID\u0020attribute\u0020for\u0020this\u0020link",
            "url": "classes/gorriecoe-Link-Extensions-AutomaticMarkupID.html#method_updateIDValue"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DBStringLink",
            "name": "DBStringLink",
            "summary": "Adds\u0020methods\u0020to\u0020DBString\u0020to\u0020help\u0020manipulate\u0020the\u0020output\u0020suitable\u0020for\u0020links",
            "url": "classes/gorriecoe-Link-Extensions-DBStringLink.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DBStringLink\u003A\u003ALinkFriendly\u0028\u0029",
            "name": "LinkFriendly",
            "summary": "Provides\u0020string\u0020replace\u0020to\u0020allow\u0020link\u0020friendly\u0020urls",
            "url": "classes/gorriecoe-Link-Extensions-DBStringLink.html#method_LinkFriendly"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DBStringLink\u003A\u003AURLFriendly\u0028\u0029",
            "name": "URLFriendly",
            "summary": "",
            "url": "classes/gorriecoe-Link-Extensions-DBStringLink.html#method_URLFriendly"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DBStringLink\u003A\u003APhoneFriendly\u0028\u0029",
            "name": "PhoneFriendly",
            "summary": "Provides\u0020string\u0020replace\u0020to\u0020allow\u0020phone\u0020number\u0020friendly\u0020urls",
            "url": "classes/gorriecoe-Link-Extensions-DBStringLink.html#method_PhoneFriendly"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DefineableMarkupID",
            "name": "DefineableMarkupID",
            "summary": "Add\u0020sitetree\u0020type\u0020to\u0020link\u0020field",
            "url": "classes/gorriecoe-Link-Extensions-DefineableMarkupID.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DefineableMarkupID\u003A\u003AupdateCMSFields\u0028\u0029",
            "name": "updateCMSFields",
            "summary": "Update\u0020Fields",
            "url": "classes/gorriecoe-Link-Extensions-DefineableMarkupID.html#method_updateCMSFields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DefineableMarkupID\u003A\u003AonBeforeWrite\u0028\u0029",
            "name": "onBeforeWrite",
            "summary": "Event\u0020handler\u0020called\u0020before\u0020writing\u0020to\u0020the\u0020database.",
            "url": "classes/gorriecoe-Link-Extensions-DefineableMarkupID.html#method_onBeforeWrite"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DefineableMarkupID\u003A\u003AupdateIDValue\u0028\u0029",
            "name": "updateIDValue",
            "summary": "Renders\u0020an\u0020HTML\u0020ID\u0020attribute\u0020for\u0020this\u0020link",
            "url": "classes/gorriecoe-Link-Extensions-DefineableMarkupID.html#method_updateIDValue"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\DefineableMarkupID\u003A\u003A\u0024db",
            "name": "db",
            "summary": "Database\u0020fields",
            "url": "classes/gorriecoe-Link-Extensions-DefineableMarkupID.html#property_db"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree",
            "name": "LinkSiteTree",
            "summary": "Add\u0020sitetree\u0020type\u0020to\u0020link\u0020object",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree\u003A\u003AupdateCMSFields\u0028\u0029",
            "name": "updateCMSFields",
            "summary": "Update\u0020Fields",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html#method_updateCMSFields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree\u003A\u003AupdateIsCurrent\u0028\u0029",
            "name": "updateIsCurrent",
            "summary": "",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html#method_updateIsCurrent"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree\u003A\u003AupdateIsSection\u0028\u0029",
            "name": "updateIsSection",
            "summary": "",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html#method_updateIsSection"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree\u003A\u003AupdateIsOrphaned\u0028\u0029",
            "name": "updateIsOrphaned",
            "summary": "",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html#method_updateIsOrphaned"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree\u003A\u003A\u0024db",
            "name": "db",
            "summary": "Database\u0020fields",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html#property_db"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree\u003A\u003A\u0024has_one",
            "name": "has_one",
            "summary": "Has_one\u0020relationship",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html#property_has_one"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree\u003A\u003A\u0024types",
            "name": "types",
            "summary": "A\u0020map\u0020of\u0020object\u0020types\u0020that\u0020can\u0020be\u0020linked\u0020to\nCustom\u0020dataobjects\u0020can\u0020be\u0020added\u0020to\u0020this",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html#property_types"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\LinkSiteTree\u003A\u003A\u0024sitetree_field_label",
            "name": "sitetree_field_label",
            "summary": "Defines\u0020the\u0020label\u0020used\u0020in\u0020the\u0020sitetree\u0020dropdown.",
            "url": "classes/gorriecoe-Link-Extensions-LinkSiteTree.html#property_sitetree_field_label"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\SiteTreeLink",
            "name": "SiteTreeLink",
            "summary": "Fixes\u0020duplicate\u0020link\u0020in\u0020SiteTree",
            "url": "classes/gorriecoe-Link-Extensions-SiteTreeLink.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions\\SiteTreeLink\u003A\u003AonBeforeDuplicate\u0028\u0029",
            "name": "onBeforeDuplicate",
            "summary": "Event\u0020handler\u0020called\u0020before\u0020duplicating\u0020a\u0020sitetree\u0020object.",
            "url": "classes/gorriecoe-Link-Extensions-SiteTreeLink.html#method_onBeforeDuplicate"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinkQueryCreator",
            "name": "LinkQueryCreator",
            "summary": "LinkQueryCreator",
            "url": "classes/gorriecoe-Link-GraphQL-LinkQueryCreator.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinkQueryCreator\u003A\u003Aattributes\u0028\u0029",
            "name": "attributes",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinkQueryCreator.html#method_attributes"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinkQueryCreator\u003A\u003Aargs\u0028\u0029",
            "name": "args",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinkQueryCreator.html#method_args"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinkQueryCreator\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinkQueryCreator.html#method_type"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinkQueryCreator\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinkQueryCreator.html#method_resolve"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinksQueryCreator",
            "name": "LinksQueryCreator",
            "summary": "LinksQueryCreator",
            "url": "classes/gorriecoe-Link-GraphQL-LinksQueryCreator.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinksQueryCreator\u003A\u003Aattributes\u0028\u0029",
            "name": "attributes",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinksQueryCreator.html#method_attributes"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinksQueryCreator\u003A\u003Aargs\u0028\u0029",
            "name": "args",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinksQueryCreator.html#method_args"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinksQueryCreator\u003A\u003Atype\u0028\u0029",
            "name": "type",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinksQueryCreator.html#method_type"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinksQueryCreator\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinksQueryCreator.html#method_resolve"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinksQueryCreator\u003A\u003AFilter\u0028\u0029",
            "name": "Filter",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinksQueryCreator.html#method_Filter"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinkTypeCreator",
            "name": "LinkTypeCreator",
            "summary": "LinkTypeCreator",
            "url": "classes/gorriecoe-Link-GraphQL-LinkTypeCreator.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinkTypeCreator\u003A\u003Aattributes\u0028\u0029",
            "name": "attributes",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinkTypeCreator.html#method_attributes"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\LinkTypeCreator\u003A\u003Afields\u0028\u0029",
            "name": "fields",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-LinkTypeCreator.html#method_fields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\ScaffoldingProvider",
            "name": "ScaffoldingProvider",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-ScaffoldingProvider.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL\\ScaffoldingProvider\u003A\u003AprovideGraphQLScaffolding\u0028\u0029",
            "name": "provideGraphQLScaffolding",
            "summary": "",
            "url": "classes/gorriecoe-Link-GraphQL-ScaffoldingProvider.html#method_provideGraphQLScaffolding"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link",
            "name": "Link",
            "summary": "Link",
            "url": "classes/gorriecoe-Link-Models-Link.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetCMSFields\u0028\u0029",
            "name": "getCMSFields",
            "summary": "CMS\u0020Fields",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getCMSFields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetCMSMainFields\u0028\u0029",
            "name": "getCMSMainFields",
            "summary": "CMS\u0020Main\u0020fields\nThis\u0020is\u0020so\u0020other\u0020modules\u0020can\u0020access\u0020these\u0020fields\u0020without\u0020other\u0020tabs\u0020etc.",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getCMSMainFields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validate",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_validate"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AonBeforeWrite\u0028\u0029",
            "name": "onBeforeWrite",
            "summary": "Event\u0020handler\u0020called\u0020before\u0020writing\u0020to\u0020the\u0020database.",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_onBeforeWrite"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgqlFields\u0028\u0029",
            "name": "gqlFields",
            "summary": "Provides\u0020a\u0020quick\u0020way\u0020to\u0020define\u0020additional\u0020methods\u0020to\u0020provideGraphQLScaffolding\u0020as\u0020Fields",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_gqlFields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgqlNestedQueries\u0028\u0029",
            "name": "gqlNestedQueries",
            "summary": "Provides\u0020a\u0020quick\u0020way\u0020to\u0020define\u0020additional\u0020methods\u0020to\u0020provideGraphQLScaffolding\u0020as\u0020Nested\u0020Queries",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_gqlNestedQueries"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AaddExtraClass\u0028\u0029",
            "name": "addExtraClass",
            "summary": "Set\u0020CSS\u0020classes\u0020for\u0020templates",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_addExtraClass"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AsetClass\u0028\u0029",
            "name": "setClass",
            "summary": "This\u0020is\u0020an\u0020alias\u0020to\u0020\u007B\u0040link\u0020addExtraClass\u0028\u0029\u007D",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_setClass"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AsetStyle\u0028\u0029",
            "name": "setStyle",
            "summary": "Set\u0020style\u0020used\u0020for",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_setStyle"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetStyle\u0028\u0029",
            "name": "getStyle",
            "summary": "Get\u0020style\u0020defined\u0020by\u0020the\u0020template\u0020or\u0020admin",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getStyle"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AsetAllowedTypes\u0028\u0029",
            "name": "setAllowedTypes",
            "summary": "Sets\u0020allowed\u0020link\u0020types",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_setAllowedTypes"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetTypes\u0028\u0029",
            "name": "getTypes",
            "summary": "Returns\u0020allowed\u0020link\u0020types",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getTypes"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003Ageti18nTypes\u0028\u0029",
            "name": "geti18nTypes",
            "summary": "Returns\u0020allowed\u0020link\u0020types\u0020with\u0020translations",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_geti18nTypes"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetStyles\u0028\u0029",
            "name": "getStyles",
            "summary": "Returns\u0020available\u0020styles",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getStyles"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003Ageti18nStyles\u0028\u0029",
            "name": "geti18nStyles",
            "summary": "Returns\u0020available\u0020styles\u0020with\u0020translations",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_geti18nStyles"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetLinkURL\u0028\u0029",
            "name": "getLinkURL",
            "summary": "Works\u0020out\u0020what\u0020the\u0020URL\u0020for\u0020this\u0020link\u0020should\u0020be\u0020based\u0020on\u0020it\u0027s\u0020Type",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getLinkURL"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetClass\u0028\u0029",
            "name": "getClass",
            "summary": "Returns\u0020the\u0020css\u0020classes",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getClass"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetClassAttr\u0028\u0029",
            "name": "getClassAttr",
            "summary": "Returns\u0020the\u0020html\u0020class\u0020attribute",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getClassAttr"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetTarget\u0028\u0029",
            "name": "getTarget",
            "summary": "Returns\u0020the\u0020html\u0020target\u0020attribute",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getTarget"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetTargetAttr\u0028\u0029",
            "name": "getTargetAttr",
            "summary": "Returns\u0020the\u0020html\u0020target\u0020attribute",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getTargetAttr"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetIDValue\u0028\u0029",
            "name": "getIDValue",
            "summary": "Returns\u0020the\u0020html\u0020id\u0020attribute",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getIDValue"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetIDAttr\u0028\u0029",
            "name": "getIDAttr",
            "summary": "Renders\u0020an\u0020HTML\u0020ID\u0020attribute",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getIDAttr"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetCurrentPage\u0028\u0029",
            "name": "getCurrentPage",
            "summary": "Returns\u0020the\u0020current\u0020page\u0020scope",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getCurrentPage"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AisCurrent\u0028\u0029",
            "name": "isCurrent",
            "summary": "Returns\u0020true\u0020if\u0020this\u0020is\u0020the\u0020currently\u0020active\u0020page\u0020being\u0020used\u0020to\u0020handle\u0020this\u0020request.",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_isCurrent"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AisSection\u0028\u0029",
            "name": "isSection",
            "summary": "Check\u0020if\u0020this\u0020page\u0020is\u0020in\u0020the\u0020currently\u0020active\u0020section\u0020\u0028e.g.\u0020it\u0020is\u0020either\u0020current\u0020or\u0020one\u0020of\u0020its\u0020children\u0020is\ncurrently\u0020being\u0020viewed\u0029.",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_isSection"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AisOrphaned\u0028\u0029",
            "name": "isOrphaned",
            "summary": "Check\u0020if\u0020the\u0020parent\u0020of\u0020this\u0020page\u0020has\u0020been\u0020removed\u0020\u0028or\u0020made\u0020otherwise\u0020unavailable\u0029,\u0020and\u0020is\u0020still\u0020referenced\u0020by\nthis\u0020child.\u0020Any\u0020such\u0020orphaned\u0020page\u0020may\u0020still\u0020require\u0020access\u0020via\u0020the\u0020CMS,\u0020but\u0020should\u0020not\u0020be\u0020shown\u0020as\u0020accessible\nto\u0020external\u0020users.",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_isOrphaned"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003ALinkOrCurrent\u0028\u0029",
            "name": "LinkOrCurrent",
            "summary": "Return\u0020\u0022link\u0022\u0020or\u0020\u0022current\u0022\u0020depending\u0020on\u0020if\u0020this\u0020is\u0020the\u0020\u007B\u0040link\u0020Link\u003A\u003AisCurrent\u0028\u0029\u007D\u0020current\u0020page.",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_LinkOrCurrent"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003ALinkOrSection\u0028\u0029",
            "name": "LinkOrSection",
            "summary": "Return\u0020\u0022link\u0022\u0020or\u0020\u0022section\u0022\u0020depending\u0020on\u0020if\u0020this\u0020is\u0020the\u0020\u007B\u0040link\u0020Link\u003A\u003AisSection\u0028\u0029\u007D\u0020current\u0020section.",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_LinkOrSection"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003ALinkingMode\u0028\u0029",
            "name": "LinkingMode",
            "summary": "Return\u0020\u0022link\u0022,\u0020\u0022current\u0022\u0020or\u0020\u0022section\u0022\u0020depending\u0020on\u0020if\u0020this\u0020page\u0020is\u0020the\u0020current\u0020page,\u0020or\u0020not\u0020on\u0020the\u0020current\u0020page\nbut\u0020in\u0020the\u0020current\u0020section.",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_LinkingMode"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetTypeLabel\u0028\u0029",
            "name": "getTypeLabel",
            "summary": "Returns\u0020the\u0020description\u0020label\u0020of\u0020this\u0020links\u0020type",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getTypeLabel"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AbaseClassName\u0028\u0029",
            "name": "baseClassName",
            "summary": "Returns\u0020the\u0020base\u0020class\u0020without\u0020namespacing",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_baseClassName"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AforTemplate\u0028\u0029",
            "name": "forTemplate",
            "summary": "Renders\u0020an\u0020HTML\u0020anchor\u0020attribute\u0020for\u0020this\u0020link",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_forTemplate"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetLayout\u0028\u0029",
            "name": "getLayout",
            "summary": "Renders\u0020an\u0020HTML\u0020anchor\u0020tag\u0020for\u0020this\u0020link\nThis\u0020is\u0020an\u0020alias\u0020to\u0020\u007B\u0040link\u0020forTemplate\u0028\u0029\u007D",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getLayout"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AgetRenderTemplates\u0028\u0029",
            "name": "getRenderTemplates",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020rendering\u0020templates",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_getRenderTemplates"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AcanView\u0028\u0029",
            "name": "canView",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_canView"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AcanEdit\u0028\u0029",
            "name": "canEdit",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_canEdit"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AcanDelete\u0028\u0029",
            "name": "canDelete",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_canDelete"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003AcanCreate\u0028\u0029",
            "name": "canCreate",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#method_canCreate"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "Defines\u0020the\u0020database\u0020table\u0020name",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_table_name"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024db",
            "name": "db",
            "summary": "Database\u0020fields",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_db"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024has_one",
            "name": "has_one",
            "summary": "Has_one\u0020relationship",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_has_one"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024owns",
            "name": "owns",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_owns"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024summary_fields",
            "name": "summary_fields",
            "summary": "Defines\u0020summary\u0020fields\u0020commonly\u0020used\u0020in\u0020table\u0020columns\nas\u0020a\u0020quick\u0020overview\u0020of\u0020the\u0020data\u0020for\u0020this\u0020dataobject",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_summary_fields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024searchable_fields",
            "name": "searchable_fields",
            "summary": "Defines\u0020a\u0020default\u0020list\u0020of\u0020filters\u0020for\u0020the\u0020search\u0020context",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_searchable_fields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024styles",
            "name": "styles",
            "summary": "A\u0020map\u0020of\u0020styles\u0020that\u0020are\u0020available\u0020in\u0020the\u0020cms\u0020for\nusers\u0020to\u0020select\u0020from.",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_styles"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024types",
            "name": "types",
            "summary": "A\u0020map\u0020of\u0020object\u0020types\u0020that\u0020can\u0020be\u0020linked\u0020to\nCustom\u0020dataobjects\u0020can\u0020be\u0020added\u0020to\u0020this",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_types"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024allowed_types",
            "name": "allowed_types",
            "summary": "List\u0020the\u0020allowed\u0020included\u0020link\u0020types.\u0020\u0020If\u0020null\u0020all\u0020are\u0020allowed.",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_allowed_types"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024casting",
            "name": "casting",
            "summary": "Ensures\u0020that\u0020the\u0020methods\u0020are\u0020wrapped\u0020in\u0020the\u0020correct\u0020type\u0020and\nvalues\u0020are\u0020safely\u0020escaped\u0020while\u0020rendering\u0020in\u0020the\u0020template.",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_casting"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024linking_mode_default",
            "name": "linking_mode_default",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_linking_mode_default"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024linking_mode_current",
            "name": "linking_mode_current",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_linking_mode_current"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024linking_mode_section",
            "name": "linking_mode_section",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_linking_mode_section"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024link_to_folders",
            "name": "link_to_folders",
            "summary": "If\u0020false,\u0020when\u0020Type\u0020is\u0020\u0022File\u0022,\u0020folders\u0020in\u0020the\u0020TreeDropdownField\u0020will\u0020not\u0020be\u0020selectable.",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_link_to_folders"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024gql_fields",
            "name": "gql_fields",
            "summary": "Provides\u0020a\u0020quick\u0020way\u0020to\u0020define\u0020additional\u0020methods\u0020for\u0020provideGraphQLScaffolding\u0020as\u0020Fields",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_gql_fields"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024gql_nested_queries",
            "name": "gql_nested_queries",
            "summary": "Provides\u0020a\u0020quick\u0020way\u0020to\u0020define\u0020additional\u0020methods\u0020for\u0020provideGraphQLScaffolding\u0020as\u0020Nested\u0020Queries",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_gql_nested_queries"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024classes",
            "name": "classes",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_classes"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models\\Link\u003A\u003A\u0024template_style",
            "name": "template_style",
            "summary": "",
            "url": "classes/gorriecoe-Link-Models-Link.html#property_template_style"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone",
            "name": "Phone",
            "summary": "Phone",
            "url": "classes/gorriecoe-Link-View-Phone.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/gorriecoe-Link-View-Phone.html#method___construct"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003AInternational\u0028\u0029",
            "name": "International",
            "summary": "Format\u0020the\u0020phone\u0020number\u0020in\u0020international\u0020format.",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_International"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003ANational\u0028\u0029",
            "name": "National",
            "summary": "Format\u0020the\u0020phone\u0020number\u0020in\u0020national\u0020format.",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_National"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003AE164\u0028\u0029",
            "name": "E164",
            "summary": "Format\u0020the\u0020phone\u0020number\u0020in\u0020E164\u0020format",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_E164"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003ARFC3966\u0028\u0029",
            "name": "RFC3966",
            "summary": "Format\u0020the\u0020phone\u0020number\u0020in\u0020RFC3966\u0020format.",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_RFC3966"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003ATo\u0028\u0029",
            "name": "To",
            "summary": "Set\u0020the\u0020country\u0020to\u0020which\u0020the\u0020phone\u0020number\u0020belongs\u0020to.",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_To"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003AFrom\u0028\u0029",
            "name": "From",
            "summary": "Set\u0020the\u0020country\u0020the\u0020user\u0020is\u0020dialing\u0020from.",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_From"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003ALeadingZero\u0028\u0029",
            "name": "LeadingZero",
            "summary": "Sets\u0020whether\u0020this\u0020phone\u0020number\u0020uses\u0020a\u0020leading\u0020zero.",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_LeadingZero"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003ARender\u0028\u0029",
            "name": "Render",
            "summary": "",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_Render"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003AforTemplate\u0028\u0029",
            "name": "forTemplate",
            "summary": "",
            "url": "classes/gorriecoe-Link-View-Phone.html#method_forTemplate"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003A\u0024library",
            "name": "library",
            "summary": "",
            "url": "classes/gorriecoe-Link-View-Phone.html#property_library"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/gorriecoe-Link-View-Phone.html#property_instance"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003A\u0024phoneNumberFormat",
            "name": "phoneNumberFormat",
            "summary": "",
            "url": "classes/gorriecoe-Link-View-Phone.html#property_phoneNumberFormat"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003A\u0024fromCountry",
            "name": "fromCountry",
            "summary": "The\u0020country\u0020the\u0020user\u0020is\u0020dialing\u0020from.",
            "url": "classes/gorriecoe-Link-View-Phone.html#property_fromCountry"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View\\Phone\u003A\u003A\u0024default_country",
            "name": "default_country",
            "summary": "",
            "url": "classes/gorriecoe-Link-View-Phone.html#property_default_country"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Extensions",
            "name": "Extensions",
            "summary": "",
            "url": "namespaces/gorriecoe-link-extensions.html"
        },                {
            "fqsen": "\\gorriecoe\\Link",
            "name": "Link",
            "summary": "",
            "url": "namespaces/gorriecoe-link.html"
        },                {
            "fqsen": "\\gorriecoe",
            "name": "gorriecoe",
            "summary": "",
            "url": "namespaces/gorriecoe.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\GraphQL",
            "name": "GraphQL",
            "summary": "",
            "url": "namespaces/gorriecoe-link-graphql.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/gorriecoe-link-models.html"
        },                {
            "fqsen": "\\gorriecoe\\Link\\View",
            "name": "View",
            "summary": "",
            "url": "namespaces/gorriecoe-link-view.html"
        }            ]
);
