Search.appendIndex(
    [
                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\HaveIBeenPwnedPageController",
            "name": "HaveIBeenPwnedPageController",
            "summary": "Class\u0020\\Firesphere\\HaveIBeenPwned\\Controllers\\HaveIBeenPwnedPageController",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-HaveIBeenPwnedPageController.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\HaveIBeenPwnedPageController\u003A\u003AcheckEmail\u0028\u0029",
            "name": "checkEmail",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-HaveIBeenPwnedPageController.html#method_checkEmail"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\HaveIBeenPwnedPageController\u003A\u003A\u0024allowed_actions",
            "name": "allowed_actions",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-HaveIBeenPwnedPageController.html#property_allowed_actions"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\HaveIBeenPwnedPageController\u003A\u003A\u0024url_handlers",
            "name": "url_handlers",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-HaveIBeenPwnedPageController.html#property_url_handlers"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler",
            "name": "LoginHandler",
            "summary": "Class\u0020LoginHandler",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "LoginHandler\u0020constructor.",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler\u003A\u003AdoLogin\u0028\u0029",
            "name": "doLogin",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html#method_doLogin"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler\u003A\u003AlockoutMember\u0028\u0029",
            "name": "lockoutMember",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html#method_lockoutMember"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler\u003A\u003AredirectToResetPassword\u0028\u0029",
            "name": "redirectToResetPassword",
            "summary": "Invoked\u0020if\u0020password\u0020is\u0020expired\u0020and\u0020must\u0020be\u0020changed",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html#method_redirectToResetPassword"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler\u003A\u003AgetService\u0028\u0029",
            "name": "getService",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html#method_getService"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler\u003A\u003AsetService\u0028\u0029",
            "name": "setService",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html#method_setService"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler\u003A\u003AvalidateMember\u0028\u0029",
            "name": "validateMember",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html#method_validateMember"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers\\LoginHandler\u003A\u003A\u0024service",
            "name": "service",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Controllers-LoginHandler.html#property_service"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\MemberExtension",
            "name": "MemberExtension",
            "summary": "Class\u0020\\Firesphere\\HaveIBeenPwned\\Extensions\\MemberExtension",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-MemberExtension.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\MemberExtension\u003A\u003AupdateCMSFields\u0028\u0029",
            "name": "updateCMSFields",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-MemberExtension.html#method_updateCMSFields"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\MemberExtension\u003A\u003AbreachFound\u0028\u0029",
            "name": "breachFound",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-MemberExtension.html#method_breachFound"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\MemberExtension\u003A\u003AbreachedSites\u0028\u0029",
            "name": "breachedSites",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-MemberExtension.html#method_breachedSites"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\MemberExtension\u003A\u003APWND_TAB",
            "name": "PWND_TAB",
            "summary": "Name\u0020of\u0020the\u0020tab\u0020that\u0020is\u0020used\u0020for\u0020HaveIBeenPwned",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-MemberExtension.html#constant_PWND_TAB"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\MemberExtension\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-MemberExtension.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\MemberExtension\u003A\u003A\u0024fallbackHelp",
            "name": "fallbackHelp",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-MemberExtension.html#property_fallbackHelp"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension",
            "name": "PasswordValidatorExtension",
            "summary": "Class\u0020\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension\u003A\u003AupdateValidatePassword\u0028\u0029",
            "name": "updateValidatePassword",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html#method_updateValidatePassword"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension\u003A\u003AcheckPwnCount\u0028\u0029",
            "name": "checkPwnCount",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html#method_checkPwnCount"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension\u003A\u003AcheckPwndSites\u0028\u0029",
            "name": "checkPwndSites",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html#method_checkPwndSites"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension\u003A\u003AgetParams\u0028\u0029",
            "name": "getParams",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html#method_getParams"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension\u003A\u003AsetParams\u0028\u0029",
            "name": "setParams",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html#method_setParams"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension\u003A\u003AaddMessages\u0028\u0029",
            "name": "addMessages",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html#method_addMessages"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension\u003A\u003A\u0024service",
            "name": "service",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html#property_service"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions\\PasswordValidatorExtension\u003A\u003A\u0024params",
            "name": "params",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Extensions-PasswordValidatorExtension.html#property_params"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Models\\HaveIBeenPwnedPage",
            "name": "HaveIBeenPwnedPage",
            "summary": "Class\u0020\\Firesphere\\HaveIBeenPwned\\Models\\HaveIBeenPwnedPage",
            "url": "classes/Firesphere-HaveIBeenPwned-Models-HaveIBeenPwnedPage.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Models\\HaveIBeenPwnedPage\u003A\u003AgetControllerName\u0028\u0029",
            "name": "getControllerName",
            "summary": "Get\u0020the\u0020controller\u0020name\u0020for\u0020this\u0020page",
            "url": "classes/Firesphere-HaveIBeenPwned-Models-HaveIBeenPwnedPage.html#method_getControllerName"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Models\\HaveIBeenPwnedPage\u003A\u003AcanCreate\u0028\u0029",
            "name": "canCreate",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Models-HaveIBeenPwnedPage.html#method_canCreate"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Models\\HaveIBeenPwnedPage\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Models-HaveIBeenPwnedPage.html#property_table_name"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService",
            "name": "HaveIBeenPwnedService",
            "summary": "Class\u0020HaveIBeenPwnedService",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HaveIBeenPwnedService\u0020constructor.",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003AcheckPwnedPassword\u0028\u0029",
            "name": "checkPwnedPassword",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#method_checkPwnedPassword"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003AcheckList\u0028\u0029",
            "name": "checkList",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#method_checkList"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003AcheckPwnedEmail\u0028\u0029",
            "name": "checkPwnedEmail",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#method_checkPwnedEmail"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003AcheckBreaches\u0028\u0029",
            "name": "checkBreaches",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#method_checkBreaches"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003AgetArgs\u0028\u0029",
            "name": "getArgs",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#method_getArgs"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003AsetArgs\u0028\u0029",
            "name": "setArgs",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#method_setArgs"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003APWND_URL",
            "name": "PWND_URL",
            "summary": "Api\u0020endpoint\u0020emails",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#constant_PWND_URL"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003APWND_API_URL",
            "name": "PWND_API_URL",
            "summary": "API\u0020endpoint\u0020passwords",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#constant_PWND_API_URL"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003AAPI_VERSION",
            "name": "API_VERSION",
            "summary": "API\u0020Version",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#constant_API_VERSION"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003AUSER_AGENT",
            "name": "USER_AGENT",
            "summary": "Useragent",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#constant_USER_AGENT"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003A\u0024allow_pwnd",
            "name": "allow_pwnd",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#property_allow_pwnd"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003A\u0024save_pwnd",
            "name": "save_pwnd",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#property_save_pwnd"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services\\HaveIBeenPwnedService\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/Firesphere-HaveIBeenPwned-Services-HaveIBeenPwnedService.html#property_args"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/firesphere-haveibeenpwned-controllers.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned",
            "name": "HaveIBeenPwned",
            "summary": "",
            "url": "namespaces/firesphere-haveibeenpwned.html"
        },                {
            "fqsen": "\\Firesphere",
            "name": "Firesphere",
            "summary": "",
            "url": "namespaces/firesphere.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Extensions",
            "name": "Extensions",
            "summary": "",
            "url": "namespaces/firesphere-haveibeenpwned-extensions.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/firesphere-haveibeenpwned-models.html"
        },                {
            "fqsen": "\\Firesphere\\HaveIBeenPwned\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/firesphere-haveibeenpwned-services.html"
        }            ]
);
