Search.appendIndex(
    [
                {
            "fqsen": "\\Firesphere\\Mailjet\\Exception\\MailjetMailerException",
            "name": "MailjetMailerException",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Exception-MailjetMailerException.html"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer",
            "name": "MailjetMailer",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer\u003A\u003A\u0024send",
            "name": "send",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html#property_send"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer\u003A\u003AaddMail\u0028\u0029",
            "name": "addMail",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html#method_addMail"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer\u003A\u003AsetSend\u0028\u0029",
            "name": "setSend",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html#method_setSend"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer\u003A\u003AsetSandbox\u0028\u0029",
            "name": "setSandbox",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html#method_setSandbox"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer\u003A\u003A\u0024service",
            "name": "service",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html#property_service"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer\u003A\u003A\u0024messages",
            "name": "messages",
            "summary": "List\u0020of\u0020Mailjet\u002Dformatted\u0020emails",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html#property_messages"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service\\MailjetMailer\u003A\u003A\u0024sandbox",
            "name": "sandbox",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Service-MailjetMailer.html#property_sandbox"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Task\\MailjetTestmailer",
            "name": "MailjetTestmailer",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Task-MailjetTestmailer.html"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Task\\MailjetTestmailer\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Task-MailjetTestmailer.html#method_run"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Task\\MailjetTestmailer\u003A\u003A\u0024segment",
            "name": "segment",
            "summary": "",
            "url": "classes/Firesphere-Mailjet-Task-MailjetTestmailer.html#property_segment"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/firesphere-mailjet-exception.html"
        },                {
            "fqsen": "\\Firesphere\\Mailjet",
            "name": "Mailjet",
            "summary": "",
            "url": "namespaces/firesphere-mailjet.html"
        },                {
            "fqsen": "\\Firesphere",
            "name": "Firesphere",
            "summary": "",
            "url": "namespaces/firesphere.html"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Service",
            "name": "Service",
            "summary": "",
            "url": "namespaces/firesphere-mailjet-service.html"
        },                {
            "fqsen": "\\Firesphere\\Mailjet\\Task",
            "name": "Task",
            "summary": "",
            "url": "namespaces/firesphere-mailjet-task.html"
        }            ]
);
