Search.appendIndex(
    [
                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtension",
            "name": "DataObjectElasticExtension",
            "summary": "Class\u0020\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtension",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtension.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtension\u003A\u003AonAfterDelete\u0028\u0029",
            "name": "onAfterDelete",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtension.html#method_onAfterDelete"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtension\u003A\u003AgetDeleteQuery\u0028\u0029",
            "name": "getDeleteQuery",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtension.html#method_getDeleteQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtension\u003A\u003AexecuteQuery\u0028\u0029",
            "name": "executeQuery",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtension.html#method_executeQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtension\u003A\u003AonAfterWrite\u0028\u0029",
            "name": "onAfterWrite",
            "summary": "Reindex\u0020after\u0020write,\u0020if\u0020it\u0027s\u0020an\u0020indexed\u0020new\/updated\u0020object",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtension.html#method_onAfterWrite"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtension\u003A\u003AdoIndex\u0028\u0029",
            "name": "doIndex",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtension.html#method_doIndex"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\ElasticSynonymExtension",
            "name": "ElasticSynonymExtension",
            "summary": "Class\u0020\\Firesphere\\ElasticSearch\\Extensions\\ElasticSynonymExtension",
            "url": "classes/Firesphere-ElasticSearch-Extensions-ElasticSynonymExtension.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\ElasticSynonymExtension\u003A\u003AupdateCMSFields\u0028\u0029",
            "name": "updateCMSFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-ElasticSynonymExtension.html#method_updateCMSFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\ElasticSynonymExtension\u003A\u003AonAfterWrite\u0028\u0029",
            "name": "onAfterWrite",
            "summary": "Add\u0020or\u0020update\u0020this\u0020synonym\u0020in\u0020Elastic",
            "url": "classes/Firesphere-ElasticSearch-Extensions-ElasticSynonymExtension.html#method_onAfterWrite"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\ElasticSynonymExtension\u003A\u003AonAfterDelete\u0028\u0029",
            "name": "onAfterDelete",
            "summary": "When\u0020deleting\u0020a\u0020synonym\u0020from\u0020the\u0020CMS,\u0020delete\u0020it\u0020as\u0020a\u0020rule",
            "url": "classes/Firesphere-ElasticSearch-Extensions-ElasticSynonymExtension.html#method_onAfterDelete"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Factories\\DocumentFactory",
            "name": "DocumentFactory",
            "summary": "Class\u0020DocumentFactory\nFactory\u0020to\u0020create\u0020documents\u0020to\u0020be\u0020pushed\u0020to\u0020Elastic",
            "url": "classes/Firesphere-ElasticSearch-Factories-DocumentFactory.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Factories\\DocumentFactory\u003A\u003AbuildItems\u0028\u0029",
            "name": "buildItems",
            "summary": "Note,\u0020it\u0020can\u0020only\u0020take\u0020one\u0020type\u0020of\u0020class\u0020at\u0020a\u0020time\u0021\nSo\u0020make\u0020sure\u0020you\u0020properly\u0020loop\u0020and\u0020set\u0020\u0024class",
            "url": "classes/Firesphere-ElasticSearch-Factories-DocumentFactory.html#method_buildItems"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Factories\\DocumentFactory\u003A\u003AbuildFields\u0028\u0029",
            "name": "buildFields",
            "summary": "Create\u0020the\u0020required\u0020record\u0020for\u0020a\u0020field",
            "url": "classes/Firesphere-ElasticSearch-Factories-DocumentFactory.html#method_buildFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Factories\\DocumentFactory\u003A\u003AaddField\u0028\u0029",
            "name": "addField",
            "summary": "Add\u0020a\u0020single\u0020field\u0020to\u0020the\u0020Elastic\u0020index",
            "url": "classes/Firesphere-ElasticSearch-Factories-DocumentFactory.html#method_addField"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Factories\\DocumentFactory\u003A\u003AaddToDoc\u0028\u0029",
            "name": "addToDoc",
            "summary": "Push\u0020field\u0020to\u0020a\u0020document",
            "url": "classes/Firesphere-ElasticSearch-Factories-DocumentFactory.html#method_addToDoc"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Factories\\DocumentFactory\u003A\u003ArecursiveImplode\u0028\u0029",
            "name": "recursiveImplode",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Factories-DocumentFactory.html#method_recursiveImplode"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Factories\\DocumentFactory\u003A\u003AaddDefaultFields\u0028\u0029",
            "name": "addDefaultFields",
            "summary": "Add\u0020fields\u0020that\u0020should\u0020always\u0020be\u0020included",
            "url": "classes/Firesphere-ElasticSearch-Factories-DocumentFactory.html#method_addDefaultFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Helpers\\ElasticLogger",
            "name": "ElasticLogger",
            "summary": "Class\u0020SearchLogger",
            "url": "classes/Firesphere-ElasticSearch-Helpers-ElasticLogger.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Helpers\\ElasticLogger\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Helpers-ElasticLogger.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex",
            "name": "ElasticIndex",
            "summary": "Base\u0020for\u0020managing\u0020a\u0020Elastic\u0020core.",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Required\u0020to\u0020initialise\u0020the\u0020fields.",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_init"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003AgetIndexName\u0028\u0029",
            "name": "getIndexName",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_getIndexName"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003AgetClasses\u0028\u0029",
            "name": "getClasses",
            "summary": "Get\u0020classes",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_getClasses"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003AinitFromConfig\u0028\u0029",
            "name": "initFromConfig",
            "summary": "Generate\u0020the\u0020config\u0020from\u0020yml\u0020if\u0020possible",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_initFromConfig"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003AsetClasses\u0028\u0029",
            "name": "setClasses",
            "summary": "Set\u0020the\u0020classes",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_setClasses"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003AdoSearch\u0028\u0029",
            "name": "doSearch",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_doSearch"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003AaddClass\u0028\u0029",
            "name": "addClass",
            "summary": "Add\u0020a\u0020class\u0020to\u0020index\u0020or\u0020query\n\u0024options\u0020is\u0020not\u0020used\u0020anymore,\u0020added\u0020for\u0020backward\u0020compatibility",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_addClass"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003AgetClientQuery\u0028\u0029",
            "name": "getClientQuery",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_getClientQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003AsetClientQuery\u0028\u0029",
            "name": "setClientQuery",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#method_setClientQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003A\u0024clientQuery",
            "name": "clientQuery",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#property_clientQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes\\ElasticIndex\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Indexes-ElasticIndex.html#property_class"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Models\\SynonymSet",
            "name": "SynonymSet",
            "summary": "Class\u0020\\Firesphere\\ElasticSearch\\Models\\SynonymSet",
            "url": "classes/Firesphere-ElasticSearch-Models-SynonymSet.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Models\\SynonymSet\u003A\u003ArequireDefaultRecords\u0028\u0029",
            "name": "requireDefaultRecords",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Models-SynonymSet.html#method_requireDefaultRecords"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Models\\SynonymSet\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Models-SynonymSet.html#property_table_name"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Models\\SynonymSet\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Models-SynonymSet.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery",
            "name": "ElasticQuery",
            "summary": "Class\u0020BaseQuery\u0020is\u0020the\u0020base\u0020of\u0020every\u0020query\u0020executed.",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AgetSort\u0028\u0029",
            "name": "getSort",
            "summary": "Get\u0020the\u0020sort\u0020fields",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_getSort"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AsetSort\u0028\u0029",
            "name": "setSort",
            "summary": "Set\u0020the\u0020sort\u0020fields",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_setSort"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AgetTerms\u0028\u0029",
            "name": "getTerms",
            "summary": "Get\u0020the\u0020search\u0020terms",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_getTerms"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AsetTerms\u0028\u0029",
            "name": "setTerms",
            "summary": "Set\u0020the\u0020search\u0020tearms",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_setTerms"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AaddTerm\u0028\u0029",
            "name": "addTerm",
            "summary": "Each\u0020boosted\u0020query\u0020needs\u0020a\u0020separate\u0020addition\u0021\ne.g.\u0020\u0024this\u002D\u003EaddTerm\u0028\u0027test\u0027,\u0020\u005B\u0027MyField\u0027,\u0020\u0027MyOtherField\u0027\u005D,\u00203\u0029\nfollowed\u0020by\n\u0024this\u002D\u003EaddTerm\u0028\u0027otherTest\u0027,\u0020\u005B\u0027Title\u0027\u005D,\u00205\u0029\u003B",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_addTerm"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AaddFilter\u0028\u0029",
            "name": "addFilter",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_addFilter"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AgetFilters\u0028\u0029",
            "name": "getFilters",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_getFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AsetFilters\u0028\u0029",
            "name": "setFilters",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_setFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AgetOrFilters\u0028\u0029",
            "name": "getOrFilters",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_getOrFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AsetOrFilters\u0028\u0029",
            "name": "setOrFilters",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_setOrFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AaddOrFilters\u0028\u0029",
            "name": "addOrFilters",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_addOrFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AgetBoostedFields\u0028\u0029",
            "name": "getBoostedFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_getBoostedFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AsetBoostedFields\u0028\u0029",
            "name": "setBoostedFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_setBoostedFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AaddBoostedField\u0028\u0029",
            "name": "addBoostedField",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_addBoostedField"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AisHighlight\u0028\u0029",
            "name": "isHighlight",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_isHighlight"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003AsetHighlight\u0028\u0029",
            "name": "setHighlight",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#method_setHighlight"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003A\u0024sort",
            "name": "sort",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#property_sort"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003A\u0024spellcheck",
            "name": "spellcheck",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#property_spellcheck"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003A\u0024filters",
            "name": "filters",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#property_filters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003A\u0024orFilters",
            "name": "orFilters",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#property_orFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003A\u0024facetsMinCount",
            "name": "facetsMinCount",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#property_facetsMinCount"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003A\u0024terms",
            "name": "terms",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#property_terms"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003A\u0024boostedFields",
            "name": "boostedFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#property_boostedFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\ElasticQuery\u003A\u003A\u0024highlight",
            "name": "highlight",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-ElasticQuery.html#property_highlight"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder",
            "name": "QueryBuilder",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AbuildQuery\u0028\u0029",
            "name": "buildQuery",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_buildQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_init"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AsetIndex\u0028\u0029",
            "name": "setIndex",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_setIndex"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AsetQuery\u0028\u0029",
            "name": "setQuery",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_setQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AgetFilters\u0028\u0029",
            "name": "getFilters",
            "summary": "Build\u0020the\u0020\u0060OR\u0060\u0020and\u0020\u0060AND\u0060\u0020filters",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_getFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AgetAndFilters\u0028\u0029",
            "name": "getAndFilters",
            "summary": "Required\u0020must\u002Dbe\u0020filters\u0020if\u0020they\u0027re\u0020here.",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_getAndFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AgetOrFilters\u0028\u0029",
            "name": "getOrFilters",
            "summary": "Create\u0020the\u0020\u0022should\u0022\u0020filter,\u0020that\u0020is\u0020OR\u0020instead\u0020of\u0020AND",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_getOrFilters"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AgetUserQuery\u0028\u0029",
            "name": "getUserQuery",
            "summary": "this\u0020allows\u0020for\u0020multiple\u0020search\u0020terms\u0020to\u0020be\u0020entered",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_getUserQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AgetFieldBoosting\u0028\u0029",
            "name": "getFieldBoosting",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_getFieldBoosting"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AaddShould\u0028\u0029",
            "name": "addShould",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_addShould"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AgetHighlighter\u0028\u0029",
            "name": "getHighlighter",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_getHighlighter"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003AsuggestList\u0028\u0029",
            "name": "suggestList",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#method_suggestList"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#property_query"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders\\QueryBuilder\u003A\u003A\u0024index",
            "name": "index",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-Builders-QueryBuilder.html#property_index"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult",
            "name": "SearchResult",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "SearchResult\u0020constructor.",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AsetSpellcheck\u0028\u0029",
            "name": "setSpellcheck",
            "summary": "Set\u0020the\u0020spellcheck\u0020list\u0020as\u0020an\u0020ArrayList",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_setSpellcheck"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AgetPaginatedMatches\u0028\u0029",
            "name": "getPaginatedMatches",
            "summary": "Get\u0020the\u0020matches\u0020as\u0020a\u0020Paginated\u0020List",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_getPaginatedMatches"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AgetMatches\u0028\u0029",
            "name": "getMatches",
            "summary": "Get\u0020the\u0020matches\u0020as\u0020an\u0020ArrayList\u0020and\u0020add\u0020an\u0020excerpt\u0020if\u0020possible.",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_getMatches"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AsetMatches\u0028\u0029",
            "name": "setMatches",
            "summary": "Set\u0020the\u0020matches\u0020from\u0020Solarium\u0020as\u0020an\u0020ArrayList",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_setMatches"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AasDataobject\u0028\u0029",
            "name": "asDataobject",
            "summary": "Check\u0020if\u0020the\u0020match\u0020is\u0020a\u0020DataObject\u0020and\u0020exists\nAnd,\u0020if\u0020so,\u0020return\u0020the\u0020found\u0020DO.",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_asDataobject"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AcreateExcerpt\u0028\u0029",
            "name": "createExcerpt",
            "summary": "Generate\u0020an\u0020excerpt\u0020for\u0020a\u0020DataObject",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_createExcerpt"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AgetHighlightByID\u0028\u0029",
            "name": "getHighlightByID",
            "summary": "Get\u0020the\u0020highlight\u0020for\u0020a\u0020specific\u0020document",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_getHighlightByID"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AsetCustomisedMatches\u0028\u0029",
            "name": "setCustomisedMatches",
            "summary": "Allow\u0020overriding\u0020of\u0020matches\u0020with\u0020a\u0020custom\u0020result.\u0020Accepts\u0020anything\u0020you\u0020like,\u0020mostly",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_setCustomisedMatches"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AcreateFacet\u0028\u0029",
            "name": "createFacet",
            "summary": "\u007B\u0040inheritDoc\u007D",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_createFacet"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003AaddHighlight\u0028\u0029",
            "name": "addHighlight",
            "summary": "Elastic\u0020is\u0020better\u0020off\u0020using\u0020the\u0020add\u0020method,\u0020as\u0020the\u0020highlights\u0020don\u0027t\u0020come\u0020in\u0020a\nsingle\u0020bulk",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#method_addHighlight"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#property_query"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003A\u0024index",
            "name": "index",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#property_index"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003A\u0024matches",
            "name": "matches",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#property_matches"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results\\SearchResult\u003A\u003A\u0024elasticResult",
            "name": "elasticResult",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Results-SearchResult.html#property_elasticResult"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService",
            "name": "ElasticCoreService",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AgetEndpointConfig\u0028\u0029",
            "name": "getEndpointConfig",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#method_getEndpointConfig"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AgetBuilder\u0028\u0029",
            "name": "getBuilder",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#method_getBuilder"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#method_getClient"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AsetClient\u0028\u0029",
            "name": "setClient",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#method_setClient"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AupdateIndex\u0028\u0029",
            "name": "updateIndex",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#method_updateIndex"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AgetFactory\u0028\u0029",
            "name": "getFactory",
            "summary": "Get\u0020the\u0020document\u0020factory\u0020prepared",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#method_getFactory"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AbuildBody\u0028\u0029",
            "name": "buildBody",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#method_buildBody"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AID_KEY",
            "name": "ID_KEY",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#constant_ID_KEY"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003AENVIRONMENT_VARS",
            "name": "ENVIRONMENT_VARS",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#constant_ENVIRONMENT_VARS"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services\\ElasticCoreService\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Services-ElasticCoreService.html#property_client"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\BulkDeleteTask",
            "name": "BulkDeleteTask",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-BulkDeleteTask.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\BulkDeleteTask\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-BulkDeleteTask.html#method_run"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\BulkDeleteTask\u003A\u003A\u0024segment",
            "name": "segment",
            "summary": "URLSegment\u0020of\u0020this\u0020task",
            "url": "classes/Firesphere-ElasticSearch-Tasks-BulkDeleteTask.html#property_segment"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\BulkDeleteTask\u003A\u003A\u0024title",
            "name": "title",
            "summary": "My\u0020name",
            "url": "classes/Firesphere-ElasticSearch-Tasks-BulkDeleteTask.html#property_title"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\BulkDeleteTask\u003A\u003A\u0024description",
            "name": "description",
            "summary": "What\u0020do\u0020I\u0020do\u003F",
            "url": "classes/Firesphere-ElasticSearch-Tasks-BulkDeleteTask.html#property_description"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\BulkDeleteTask\u003A\u003A\u0024enabled",
            "name": "enabled",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-BulkDeleteTask.html#property_enabled"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticConfigureSynonymsTask",
            "name": "ElasticConfigureSynonymsTask",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticConfigureSynonymsTask.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticConfigureSynonymsTask\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticConfigureSynonymsTask.html#method_run"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticConfigureSynonymsTask\u003A\u003AtransformBaseSynonyms\u0028\u0029",
            "name": "transformBaseSynonyms",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticConfigureSynonymsTask.html#method_transformBaseSynonyms"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticConfigureSynonymsTask\u003A\u003A\u0024segment",
            "name": "segment",
            "summary": "URLSegment\u0020of\u0020this\u0020task",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticConfigureSynonymsTask.html#property_segment"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticConfigureSynonymsTask\u003A\u003A\u0024title",
            "name": "title",
            "summary": "My\u0020name",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticConfigureSynonymsTask.html#property_title"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticConfigureSynonymsTask\u003A\u003A\u0024description",
            "name": "description",
            "summary": "What\u0020do\u0020I\u0020do\u003F",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticConfigureSynonymsTask.html#property_description"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask",
            "name": "ElasticIndexTask",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "SolrIndexTask\u0020constructor.\u0020Sets\u0020up\u0020the\u0020document\u0020factory",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_run"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AgetLogger\u0028\u0029",
            "name": "getLogger",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_getLogger"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_setLogger"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AgetClasses\u0028\u0029",
            "name": "getClasses",
            "summary": "get\u0020the\u0020classes\u0020to\u0020run\u0020for\u0020this\u0020task\u0020execution",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_getClasses"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AgetService\u0028\u0029",
            "name": "getService",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_getService"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AsetService\u0028\u0029",
            "name": "setService",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_setService"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AisDebug\u0028\u0029",
            "name": "isDebug",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_isDebug"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AsetDebug\u0028\u0029",
            "name": "setDebug",
            "summary": "Set\u0020the\u0020debug\u0020mode",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_setDebug"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AindexClass\u0028\u0029",
            "name": "indexClass",
            "summary": "Index\u0020a\u0020single\u0020class\u0020for\u0020a\u0020given\u0020index.\u0020\u007B\u0040link\u0020static\u003A\u003AindexClassForIndex\u0028\u0029\u007D",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_indexClass"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AgetIndex\u0028\u0029",
            "name": "getIndex",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_getIndex"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AsetIndex\u0028\u0029",
            "name": "setIndex",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_setIndex"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AdoReindex\u0028\u0029",
            "name": "doReindex",
            "summary": "Reindex\u0020the\u0020given\u0020group,\u0020for\u0020each\u0020state",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_doReindex"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AindexStateClass\u0028\u0029",
            "name": "indexStateClass",
            "summary": "Index\u0020a\u0020group\u0020of\u0020a\u0020class\u0020for\u0020a\u0020specific\u0020state\u0020and\u0020index",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_indexStateClass"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003AupdateIndex\u0028\u0029",
            "name": "updateIndex",
            "summary": "Execute\u0020the\u0020update\u0020on\u0020the\u0020client",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#method_updateIndex"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A\u0024segment",
            "name": "segment",
            "summary": "URLSegment\u0020of\u0020this\u0020task",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#property_segment"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A\u0024currentStates",
            "name": "currentStates",
            "summary": "Store\u0020the\u0020current\u0020states\u0020for\u0020all\u0020instances\u0020of\u0020SiteState",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#property_currentStates"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A\u0024title",
            "name": "title",
            "summary": "My\u0020name",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#property_title"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A\u0024description",
            "name": "description",
            "summary": "What\u0020do\u0020I\u0020do\u003F",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#property_description"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A\u0024service",
            "name": "service",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#property_service"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#property_logger"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A\u0024debug",
            "name": "debug",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#property_debug"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTask\u003A\u003A\u0024index",
            "name": "index",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTask.html#property_index"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait",
            "name": "BaseIndexTrait",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AaddSortField\u0028\u0029",
            "name": "addSortField",
            "summary": "Add\u0020a\u0020field\u0020to\u0020sort\u0020on",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_addSortField"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AgetFulltextFields\u0028\u0029",
            "name": "getFulltextFields",
            "summary": "Get\u0020the\u0020fulltext\u0020fields",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_getFulltextFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AsetFulltextFields\u0028\u0029",
            "name": "setFulltextFields",
            "summary": "Set\u0020the\u0020fulltext\u0020fields",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_setFulltextFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AgetFilterFields\u0028\u0029",
            "name": "getFilterFields",
            "summary": "Get\u0020the\u0020filter\u0020fields",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_getFilterFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AsetFilterFields\u0028\u0029",
            "name": "setFilterFields",
            "summary": "Set\u0020the\u0020filter\u0020fields",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_setFilterFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AaddFulltextField\u0028\u0029",
            "name": "addFulltextField",
            "summary": "Add\u0020a\u0020single\u0020Fulltext\u0020field",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_addFulltextField"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AgetSortFields\u0028\u0029",
            "name": "getSortFields",
            "summary": "Get\u0020the\u0020sortable\u0020fields",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_getSortFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AsetSortFields\u0028\u0029",
            "name": "setSortFields",
            "summary": "Set\/override\u0020the\u0020sortable\u0020fields",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_setSortFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AaddAllFulltextFields\u0028\u0029",
            "name": "addAllFulltextFields",
            "summary": "Add\u0020all\u0020text\u002Dtype\u0020fields\u0020to\u0020the\u0020given\u0020index",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_addAllFulltextFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AaddAllFieldsByType\u0028\u0029",
            "name": "addAllFieldsByType",
            "summary": "Add\u0020all\u0020database\u002Dbacked\u0020text\u0020fields\u0020as\u0020fulltext\u0020searchable\u0020fields.",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_addAllFieldsByType"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AgetClasses\u0028\u0029",
            "name": "getClasses",
            "summary": "This\u0020trait\u0020requires\u0020classes\u0020to\u0020be\u0020set,\u0020so\u0020getClasses\u0020can\u0020be\u0020called.",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_getClasses"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AaddFulltextFieldsForClass\u0028\u0029",
            "name": "addFulltextFieldsForClass",
            "summary": "Add\u0020all\u0020fields\u0020of\u0020a\u0020given\u0020type\u0020to\u0020the\u0020index",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_addFulltextFieldsForClass"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AaddAllDateFields\u0028\u0029",
            "name": "addAllDateFields",
            "summary": "Add\u0020all\u0020date\u002Dtype\u0020fields\u0020to\u0020the\u0020given\u0020index",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_addAllDateFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AaddFacetField\u0028\u0029",
            "name": "addFacetField",
            "summary": "Add\u0020a\u0020facet\u0020field",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_addFacetField"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AaddFilterField\u0028\u0029",
            "name": "addFilterField",
            "summary": "Add\u0020a\u0020filterable\u0020field",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_addFilterField"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_getClient"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003AsetClient\u0028\u0029",
            "name": "setClient",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#method_setClient"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#property_client"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003A\u0024facetFields",
            "name": "facetFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#property_facetFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003A\u0024fulltextFields",
            "name": "fulltextFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#property_fulltextFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003A\u0024filterFields",
            "name": "filterFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#property_filterFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003A\u0024sortFields",
            "name": "sortFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#property_sortFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003A\u0024storedFields",
            "name": "storedFields",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#property_storedFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits\\BaseIndexTrait\u003A\u003A\u0024usedAllFields",
            "name": "usedAllFields",
            "summary": "usedAllFields\u0020is\u0020used\u0020to\u0020determine\u0020if\u0020the\u0020addAllFields\u0020method\u0020has\u0020been\u0020called\nThis\u0020is\u0020to\u0020prevent\u0020a\u0020notice\u0020if\u0020there\u0020is\u0020no\u0020yml.",
            "url": "classes/Firesphere-ElasticSearch-Traits-IndexTraits-BaseIndexTrait.html#property_usedAllFields"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\EndToEndTest",
            "name": "EndToEndTest",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-EndToEndTest.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\EndToEndTest\u003A\u003AtestSearching\u0028\u0029",
            "name": "testSearching",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-EndToEndTest.html#method_testSearching"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtensionTest",
            "name": "DataObjectElasticExtensionTest",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtensionTest.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtensionTest\u003A\u003AtestCreatingObject\u0028\u0029",
            "name": "testCreatingObject",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtensionTest.html#method_testCreatingObject"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtensionTest\u003A\u003AtestOnAfterDelete\u0028\u0029",
            "name": "testOnAfterDelete",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtensionTest.html#method_testOnAfterDelete"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions\\DataObjectElasticExtensionTest\u003A\u003A\u0024usesDatabase",
            "name": "usesDatabase",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Extensions-DataObjectElasticExtensionTest.html#property_usesDatabase"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\SynonymSetTest",
            "name": "SynonymSetTest",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-SynonymSetTest.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\SynonymSetTest\u003A\u003AtestRequireDefaultRecords\u0028\u0029",
            "name": "testRequireDefaultRecords",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-SynonymSetTest.html#method_testRequireDefaultRecords"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\SynonymSetTest\u003A\u003A\u0024usesDatabase",
            "name": "usesDatabase",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-SynonymSetTest.html#property_usesDatabase"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\QueryBuilderTest",
            "name": "QueryBuilderTest",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-QueryBuilderTest.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\QueryBuilderTest\u003A\u003AtestBuildQuery\u0028\u0029",
            "name": "testBuildQuery",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-QueryBuilderTest.html#method_testBuildQuery"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\QueryBuilderTest\u003A\u003A\u0024expected_query",
            "name": "expected_query",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Queries-QueryBuilderTest.html#property_expected_query"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\ElasticCoreServiceTest",
            "name": "ElasticCoreServiceTest",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-ElasticCoreServiceTest.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\ElasticCoreServiceTest\u003A\u003AtestConstruct\u0028\u0029",
            "name": "testConstruct",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-ElasticCoreServiceTest.html#method_testConstruct"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\ElasticCoreServiceTest\u003A\u003AtestUpdateIndex\u0028\u0029",
            "name": "testUpdateIndex",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-ElasticCoreServiceTest.html#method_testUpdateIndex"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests\\ElasticCoreServiceTest\u003A\u003A\u0024usesDatabase",
            "name": "usesDatabase",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tests-ElasticCoreServiceTest.html#property_usesDatabase"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ConfigureSynonymsTaskTest",
            "name": "ConfigureSynonymsTaskTest",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ConfigureSynonymsTaskTest.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ConfigureSynonymsTaskTest\u003A\u003AtestRun\u0028\u0029",
            "name": "testRun",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ConfigureSynonymsTaskTest.html#method_testRun"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ConfigureSynonymsTaskTest\u003A\u003A\u0024usesDatabase",
            "name": "usesDatabase",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ConfigureSynonymsTaskTest.html#property_usesDatabase"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTaskTest",
            "name": "ElasticIndexTaskTest",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTaskTest.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTaskTest\u003A\u003AtestConstruct\u0028\u0029",
            "name": "testConstruct",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTaskTest.html#method_testConstruct"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTaskTest\u003A\u003AtestRun\u0028\u0029",
            "name": "testRun",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTaskTest.html#method_testRun"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks\\ElasticIndexTaskTest\u003A\u003A\u0024usesDatabase",
            "name": "usesDatabase",
            "summary": "",
            "url": "classes/Firesphere-ElasticSearch-Tasks-ElasticIndexTaskTest.html#property_usesDatabase"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Extensions",
            "name": "Extensions",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-extensions.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch",
            "name": "ElasticSearch",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch.html"
        },                {
            "fqsen": "\\Firesphere",
            "name": "Firesphere",
            "summary": "",
            "url": "namespaces/firesphere.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-factories.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-helpers.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Indexes",
            "name": "Indexes",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-indexes.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-models.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries",
            "name": "Queries",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-queries.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Queries\\Builders",
            "name": "Builders",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-queries-builders.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Results",
            "name": "Results",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-results.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-services.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tasks",
            "name": "Tasks",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-tasks.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits\\IndexTraits",
            "name": "IndexTraits",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-traits-indextraits.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-traits.html"
        },                {
            "fqsen": "\\Firesphere\\ElasticSearch\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/firesphere-elasticsearch-tests.html"
        }            ]
);
