Search.appendIndex(
    [
                {
            "fqsen": "\\getSuggestion\u0028\u0029",
            "name": "getSuggestion",
            "summary": "Get\u0020a\u0020suggestion\u0020from\u0020Solr",
            "url": "namespaces/default.html#function_getSuggestion"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Admins\\SearchAdmin",
            "name": "SearchAdmin",
            "summary": "Class\u0020\\Firesphere\\SearchBackend\\Admins\\SearchAdmin",
            "url": "classes/Firesphere-SearchBackend-Admins-SearchAdmin.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Admins\\SearchAdmin\u003A\u003Ainit\u0028\u0029",
            "name": "init",
            "summary": "Make\u0020sure\u0020the\u0020custom\u0020CSS\u0020for\u0020highlighting\u0020in\u0020the\u0020GridField\u0020is\u0020loaded",
            "url": "classes/Firesphere-SearchBackend-Admins-SearchAdmin.html#method_init"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Admins\\SearchAdmin\u003A\u003A\u0024menu_icon_class",
            "name": "menu_icon_class",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Admins-SearchAdmin.html#property_menu_icon_class"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Admins\\SearchAdmin\u003A\u003A\u0024url_segment",
            "name": "url_segment",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Admins-SearchAdmin.html#property_url_segment"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Admins\\SearchAdmin\u003A\u003A\u0024menu_title",
            "name": "menu_title",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Admins-SearchAdmin.html#property_menu_title"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Admins\\SearchAdmin\u003A\u003A\u0024managed_models",
            "name": "managed_models",
            "summary": "List\u0020of\u0020all\u0020managed\u0020\u007B\u0040link\u0020DataObject\u007Ds\u0020in\u0020this\u0020interface.\u0020\u007B\u0040link\u0020ModelAdmin\u003A\u003A\u0024managed_models\u007D",
            "url": "classes/Firesphere-SearchBackend-Admins-SearchAdmin.html#property_managed_models"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions\\DataObjectSearchExtension",
            "name": "DataObjectSearchExtension",
            "summary": "Class\u0020\\Firesphere\\SearchBackend\\Extensions\\DataObjectSearchExtension",
            "url": "classes/Firesphere-SearchBackend-Extensions-DataObjectSearchExtension.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions\\DataObjectSearchExtension\u003A\u003AgetViewStatus\u0028\u0029",
            "name": "getViewStatus",
            "summary": "Get\u0020the\u0020view\u0020status\u0020for\u0020each\u0020member\u0020in\u0020this\u0020object",
            "url": "classes/Firesphere-SearchBackend-Extensions-DataObjectSearchExtension.html#method_getViewStatus"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions\\DataObjectSearchExtension\u003A\u003AgetGroupViewPermissions\u0028\u0029",
            "name": "getGroupViewPermissions",
            "summary": "Determine\u0020the\u0020view\u0020permissions\u0020based\u0020on\u0020group\u0020settings",
            "url": "classes/Firesphere-SearchBackend-Extensions-DataObjectSearchExtension.html#method_getGroupViewPermissions"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions\\DataObjectSearchExtension\u003A\u003AgetDirtyClass\u0028\u0029",
            "name": "getDirtyClass",
            "summary": "Find\u0020or\u0020create\u0020a\u0020new\u0020DirtyClass\u0020for\u0020recording\u0020dirty\u0020IDs",
            "url": "classes/Firesphere-SearchBackend-Extensions-DataObjectSearchExtension.html#method_getDirtyClass"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions\\DataObjectSearchExtension\u003A\u003A\u0024cachedClasses",
            "name": "cachedClasses",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Extensions-DataObjectSearchExtension.html#property_cachedClasses"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions\\DataObjectSearchExtension\u003A\u003A\u0024siteConfig",
            "name": "siteConfig",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Extensions-DataObjectSearchExtension.html#property_siteConfig"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions\\GridFieldExtension",
            "name": "GridFieldExtension",
            "summary": "Class\u0020GridFieldExtension\nDirty\u0020hack\u0020to\u0020get\u0020the\u0020alert\/warning\/info\u0020classes\u0020in\u0020to\u0020the\u0020gridfield",
            "url": "classes/Firesphere-SearchBackend-Extensions-GridFieldExtension.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions\\GridFieldExtension\u003A\u003AupdateNewRowClasses\u0028\u0029",
            "name": "updateNewRowClasses",
            "summary": "Add\u0020the\u0020visibility\u0020classes\u0020to\u0020the\u0020GridField",
            "url": "classes/Firesphere-SearchBackend-Extensions-GridFieldExtension.html#method_updateNewRowClasses"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory",
            "name": "DocumentCoreFactory",
            "summary": "Class\u0020DocumentFactory\nFactory\u0020to\u0020create\u0020documents\u0020to\u0020be\u0020pushed\u0020to\u0020Solr",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DocumentFactory\u0020constructor,\u0020sets\u0020up\u0020the\u0020field\u0020resolver",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AbuildItems\u0028\u0029",
            "name": "buildItems",
            "summary": "Note,\u0020it\u0020can\u0020only\u0020take\u0020one\u0020type\u0020of\u0020class\u0020at\u0020a\u0020time\u0021\nSo\u0020make\u0020sure\u0020you\u0020properly\u0020loop\u0020and\u0020set\u0020\u0024class",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_buildItems"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AisDebug\u0028\u0029",
            "name": "isDebug",
            "summary": "Are\u0020we\u0020debugging\u003F",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_isDebug"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AsetDebug\u0028\u0029",
            "name": "setDebug",
            "summary": "Set\u0020to\u0020true\u0020if\u0020debugging\u0020should\u0020be\u0020enabled",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_setDebug"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AgetFieldResolver\u0028\u0029",
            "name": "getFieldResolver",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_getFieldResolver"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AsetFieldResolver\u0028\u0029",
            "name": "setFieldResolver",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_setFieldResolver"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AaddDefaultFields\u0028\u0029",
            "name": "addDefaultFields",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_addDefaultFields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AindexGroupMessage\u0028\u0029",
            "name": "indexGroupMessage",
            "summary": "Show\u0020the\u0020message\u0020about\u0020what\u0020is\u0020being\u0020indexed",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_indexGroupMessage"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AgetClass\u0028\u0029",
            "name": "getClass",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_getClass"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AsetClass\u0028\u0029",
            "name": "setClass",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_setClass"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AgetItems\u0028\u0029",
            "name": "getItems",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_getItems"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AsetItems\u0028\u0029",
            "name": "setItems",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_setItems"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AclassIs\u0028\u0029",
            "name": "classIs",
            "summary": "Determine\u0020if\u0020the\u0020given\u0020object\u0020is\u0020one\u0020of\u0020the\u0020given\u0020type",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_classIs"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AclassEquals\u0028\u0029",
            "name": "classEquals",
            "summary": "Check\u0020if\u0020a\u0020base\u0020class\u0020is\u0020an\u0020instance\u0020of\u0020the\u0020expected\u0020base\u0020group",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_classEquals"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AgetValuesForField\u0028\u0029",
            "name": "getValuesForField",
            "summary": "Use\u0020the\u0020DataResolver\u0020to\u0020find\u0020the\u0020value\u0028s\u0029\u0020for\u0020a\u0020field.",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_getValuesForField"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003AgetShortFieldName\u0028\u0029",
            "name": "getShortFieldName",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#method_getShortFieldName"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003A\u0024class",
            "name": "class",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#property_class"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#property_items"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003A\u0024fieldResolver",
            "name": "fieldResolver",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#property_fieldResolver"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003A\u0024debug",
            "name": "debug",
            "summary": "Set\u0020debug\u0020mode\u0020on\u0020or\u0020off",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#property_debug"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories\\DocumentCoreFactory\u003A\u003A\u0024keyService",
            "name": "keyService",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Factories-DocumentCoreFactory.html#property_keyService"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\DataResolver",
            "name": "DataResolver",
            "summary": "Class\u0020DataResolver",
            "url": "classes/Firesphere-SearchBackend-Helpers-DataResolver.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\DataResolver\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DataResolver\u0020constructor.",
            "url": "classes/Firesphere-SearchBackend-Helpers-DataResolver.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\DataResolver\u003A\u003Aidentify\u0028\u0029",
            "name": "identify",
            "summary": "Identify\u0020the\u0020given\u0020object\u0027s\u0020columns",
            "url": "classes/Firesphere-SearchBackend-Helpers-DataResolver.html#method_identify"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\DataResolver\u003A\u003AcannotIdentifyException\u0028\u0029",
            "name": "cannotIdentifyException",
            "summary": "An\u0020error\u0020occured,\u0020so\u0020log\u0020it",
            "url": "classes/Firesphere-SearchBackend-Helpers-DataResolver.html#method_cannotIdentifyException"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\DataResolver\u003A\u003A\u0024objTypes",
            "name": "objTypes",
            "summary": "Supported\u0020object\u0020types",
            "url": "classes/Firesphere-SearchBackend-Helpers-DataResolver.html#property_objTypes"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver",
            "name": "FieldResolver",
            "summary": "Class\u0020FieldResolver\nSome\u0020additional\u0020introspection\u0020tools\u0020that\u0020are\u0020used\u0020often\u0020by\u0020the\u0020fulltext\u0020search\u0020code",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AisSubclassOf\u0028\u0029",
            "name": "isSubclassOf",
            "summary": "Check\u0020if\u0020class\u0020is\u0020subclass\u0020of\u0020\u0028a\u0029\u0020the\u0020class\u0020in\u0020\u0024instanceOf,\u0020or\u0020\u0028b\u0029\u0020any\u0020of\u0020the\u0020classes\u0020in\u0020the\u0020array\u0020\u0024instanceOf",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_isSubclassOf"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AresolveField\u0028\u0029",
            "name": "resolveField",
            "summary": "Resolve\u0020a\u0020field\u0020ancestry",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_resolveField"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetBuildSources\u0028\u0029",
            "name": "getBuildSources",
            "summary": "Get\u0020the\u0020sources\u0020to\u0020build\u0020in\u0020to\u0020a\u0020Solr\u0020field",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getBuildSources"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetNext\u0028\u0029",
            "name": "getNext",
            "summary": "Get\u0020the\u0020next\u0020lookup\u0020item\u0020from\u0020the\u0020buildSources",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getNext"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AresolveRelation\u0028\u0029",
            "name": "resolveRelation",
            "summary": "Resolve\u0020relations\u0020if\u0020possible",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_resolveRelation"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetSourceName\u0028\u0029",
            "name": "getSourceName",
            "summary": "This\u0020is\u0020used\u0020to\u0020clean\u0020the\u0020source\u0020name\u0020from\u0020suffix\nsuffixes\u0020are\u0020needed\u0020to\u0020support\u0020multiple\u0020relations\u0020with\u0020the\u0020same\u0020name\u0020on\u0020different\u0020page\u0020types",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getSourceName"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetHierarchy\u0028\u0029",
            "name": "getHierarchy",
            "summary": "Get\u0020all\u0020the\u0020classes\u0020involved\u0020in\u0020a\u0020DataObject\u0020hierarchy\u0020\u002D\u0020both\u0020super\u0020and\u0020optionally\u0020subclasses",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getHierarchy"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetHierarchyClasses\u0028\u0029",
            "name": "getHierarchyClasses",
            "summary": "Get\u0020the\u0020hierarchy\u0020for\u0020a\u0020class",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getHierarchyClasses"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetSubClasses\u0028\u0029",
            "name": "getSubClasses",
            "summary": "Get\u0020the\u0020subclasses\u0020for\u0020the\u0020given\u0020class\nShould\u0020be\u0020replaced\u0020with\u0020PHP\u0020native\u0020methods",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getSubClasses"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AexcludeDataObjectIDx\u0028\u0029",
            "name": "excludeDataObjectIDx",
            "summary": "Objects\u0020to\u0020exclude\u0020from\u0020the\u0020index",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_excludeDataObjectIDx"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AresolveNext\u0028\u0029",
            "name": "resolveNext",
            "summary": "Resolve\u0020the\u0020next\u0020item\u0020in\u0020line\u0020to\u0020be\u0020indexed",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_resolveNext"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetRelationData\u0028\u0029",
            "name": "getRelationData",
            "summary": "Relational\u0020data",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getRelationData"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetFieldOptions\u0028\u0029",
            "name": "getFieldOptions",
            "summary": "Create\u0020field\u0020options\u0020for\u0020the\u0020given\u0020index\u0020field",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getFieldOptions"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AfindOrigin\u0028\u0029",
            "name": "findOrigin",
            "summary": "Find\u0020the\u0020origin\u0020of\u0020a\u0020field",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_findOrigin"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Get\u0020the\u0020type\u0020of\u0020this\u0020field",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getType"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetOriginForType\u0028\u0029",
            "name": "getOriginForType",
            "summary": "Extraction\u0020to\u0020find\u0020the\u0020origin\u0020for\u0020a\u0020specific\u0020type\u0020field",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getOriginForType"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003AgetFoundOriginData\u0028\u0029",
            "name": "getFoundOriginData",
            "summary": "FoundOriginData\u0020is\u0020a\u0020helper\u0020to\u0020make\u0020sure\u0020the\u0020options\u0020are\u0020properly\u0020set.",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#method_getFoundOriginData"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003A\u0024ancestry",
            "name": "ancestry",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#property_ancestry"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\FieldResolver\u003A\u003A\u0024hierarchy",
            "name": "hierarchy",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-FieldResolver.html#property_hierarchy"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\IndexingHelper",
            "name": "IndexingHelper",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-IndexingHelper.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\IndexingHelper\u003A\u003AgetGroupSettings\u0028\u0029",
            "name": "getGroupSettings",
            "summary": "Check\u0020the\u0020amount\u0020of\u0020groups\u0020and\u0020the\u0020total\u0020against\u0020the\u0020isGroup\u0020check.",
            "url": "classes/Firesphere-SearchBackend-Helpers-IndexingHelper.html#method_getGroupSettings"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\IndexingHelper\u003A\u003AgetBatchLength\u0028\u0029",
            "name": "getBatchLength",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-IndexingHelper.html#method_getBatchLength"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\IndexingHelper\u003A\u003AsetBatchLength\u0028\u0029",
            "name": "setBatchLength",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-IndexingHelper.html#method_setBatchLength"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\IndexingHelper\u003A\u003AgetCores\u0028\u0029",
            "name": "getCores",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-IndexingHelper.html#method_getCores"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\IndexingHelper\u003A\u003AsetCores\u0028\u0029",
            "name": "setCores",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-IndexingHelper.html#method_setCores"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\IndexingHelper\u003A\u003A\u0024batch_length",
            "name": "batch_length",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-IndexingHelper.html#property_batch_length"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\IndexingHelper\u003A\u003A\u0024cores",
            "name": "cores",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-IndexingHelper.html#property_cores"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\SearchLogger",
            "name": "SearchLogger",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-SearchLogger.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\SearchLogger\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-SearchLogger.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\SearchLogger\u003A\u003AlogMessage\u0028\u0029",
            "name": "logMessage",
            "summary": "Log\u0020the\u0020given\u0020message\u0020and\u0020dump\u0020it\u0020out.",
            "url": "classes/Firesphere-SearchBackend-Helpers-SearchLogger.html#method_logMessage"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\SearchLogger\u003A\u003AsaveLog\u0028\u0029",
            "name": "saveLog",
            "summary": "Save\u0020the\u0020latest\u0020Search\u0020errors\u0020to\u0020the\u0020log",
            "url": "classes/Firesphere-SearchBackend-Helpers-SearchLogger.html#method_saveLog"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\SearchLogger\u003A\u003AfindOrCreateLog\u0028\u0029",
            "name": "findOrCreateLog",
            "summary": "Attempt\u0020to\u0020find,\u0020otherwise\u0020create,\u0020a\u0020log\u0020object",
            "url": "classes/Firesphere-SearchBackend-Helpers-SearchLogger.html#method_findOrCreateLog"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\SearchLogger\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-SearchLogger.html#property_client"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\SearchLogger\u003A\u003A\u0024options",
            "name": "options",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-SearchLogger.html#property_options"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\Statics",
            "name": "Statics",
            "summary": "Class\u0020Statics\nTypemap\u0020static\u0020helper",
            "url": "classes/Firesphere-SearchBackend-Helpers-Statics.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\Statics\u003A\u003AgetTypeMap\u0028\u0029",
            "name": "getTypeMap",
            "summary": "Get\u0020the\u0020typemap\u0020for\u0020Solr\nNote\u0020that\u0020this\u0020is\u0020very\u0020Solr\u0020oriented\u0020at\u0020the\u0020moment",
            "url": "classes/Firesphere-SearchBackend-Helpers-Statics.html#method_getTypeMap"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\Statics\u003A\u003A\u0024typemap",
            "name": "typemap",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-Statics.html#property_typemap"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\Synonyms",
            "name": "Synonyms",
            "summary": "Class\u0020Synonyms\nList\u0020out\u0020UK\u0020to\u0020US\u0020synonyms\u0020and\u0020synonyms\u0020from\u0020\u007B\u0040link\u0020SiteConfig\u007D\nSource\u003A\u0020\u0040link\u0020https\u003A\/\/raw.githubusercontent.com\/heiswayi\/spelling\u002Duk\u002Dvs\u002Dus\/",
            "url": "classes/Firesphere-SearchBackend-Helpers-Synonyms.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\Synonyms\u003A\u003AgetSynonymsAsString\u0028\u0029",
            "name": "getSynonymsAsString",
            "summary": "Make\u0020the\u0020UK\u0020to\u0020US\u0020spelling\u0020synonyms\u0020as\u0020a\u0020newline\u0020separated\u0020string\nOr\u0020any\u0020other\u0020synonyms\u0020defined\u0020if\u0020the\u0020user\u0020wishes\u0020to\u0020do\u0020so",
            "url": "classes/Firesphere-SearchBackend-Helpers-Synonyms.html#method_getSynonymsAsString"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\Synonyms\u003A\u003AgetSynonyms\u0028\u0029",
            "name": "getSynonyms",
            "summary": "Get\u0020the\u0020available\u0020synonyms\u0020as\u0020an\u0020array\u0020from\u0020config\nDefaulting\u0020to\u0020adding\u0020the\u0020UK\u0020to\u0020US\u0020spelling\u0020differences",
            "url": "classes/Firesphere-SearchBackend-Helpers-Synonyms.html#method_getSynonyms"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\Synonyms\u003A\u003AgetSynonymsFlattened\u0028\u0029",
            "name": "getSynonymsFlattened",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-Synonyms.html#method_getSynonymsFlattened"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers\\Synonyms\u003A\u003A\u0024synonyms",
            "name": "synonyms",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Helpers-Synonyms.html#property_synonyms"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Indexes\\CoreIndex",
            "name": "CoreIndex",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Indexes-CoreIndex.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Indexes\\CoreIndex\u003A\u003AgetFieldsForIndexing\u0028\u0029",
            "name": "getFieldsForIndexing",
            "summary": "Get\u0020all\u0020fields\u0020that\u0020are\u0020required\u0020for\u0020indexing\u0020in\u0020a\u0020unique\u0020way",
            "url": "classes/Firesphere-SearchBackend-Indexes-CoreIndex.html#method_getFieldsForIndexing"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Indexes\\CoreIndex\u003A\u003A\u0024fieldTypes",
            "name": "fieldTypes",
            "summary": "Field\u0020types\u0020that\u0020can\u0020be\u0020added\nUsed\u0020in\u0020init\u0020to\u0020call\u0020build\u0020methods\u0020from\u0020configuration\u0020yml",
            "url": "classes/Firesphere-SearchBackend-Indexes-CoreIndex.html#property_fieldTypes"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\QueryBuilderInterface",
            "name": "QueryBuilderInterface",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Interfaces-QueryBuilderInterface.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\QueryBuilderInterface\u003A\u003AbuildQuery\u0028\u0029",
            "name": "buildQuery",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Interfaces-QueryBuilderInterface.html#method_buildQuery"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SearchResultInterface",
            "name": "SearchResultInterface",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SearchResultInterface.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SearchResultInterface\u003A\u003AgetMatches\u0028\u0029",
            "name": "getMatches",
            "summary": "Get\u0020the\u0020matches\u0020as\u0020an\u0020ArrayList\u0020and\u0020add\u0020an\u0020excerpt\u0020if\u0020possible.",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SearchResultInterface.html#method_getMatches"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SearchResultInterface\u003A\u003AgetPaginatedMatches\u0028\u0029",
            "name": "getPaginatedMatches",
            "summary": "Paginated\u0020version\u0020of\u0020getPaginatedMatches",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SearchResultInterface.html#method_getPaginatedMatches"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SearchResultInterface\u003A\u003AgetHighlightByID\u0028\u0029",
            "name": "getHighlightByID",
            "summary": "Get\u0020the\u0020highlights\u0020for\u0020a\u0020specific\u0020document",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SearchResultInterface.html#method_getHighlightByID"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SearchResultInterface\u003A\u003AgetSpellcheck\u0028\u0029",
            "name": "getSpellcheck",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SearchResultInterface.html#method_getSpellcheck"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SearchResultInterface\u003A\u003AcreateFacet\u0028\u0029",
            "name": "createFacet",
            "summary": "Create\u0020a\u0020single\u0020facet\u0020array\u0020for\u0020a\u0020faceted\u0020class",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SearchResultInterface.html#method_createFacet"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SiteStateInterface",
            "name": "SiteStateInterface",
            "summary": "Interface\u0020SiteStateInterface\u0020defines\u0020the\u0020methods\u0020every\u0020State\u0020altering\u0020must\u0020implement.",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SiteStateInterface.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SiteStateInterface\u003A\u003AstateIsApplicable\u0028\u0029",
            "name": "stateIsApplicable",
            "summary": "Is\u0020this\u0020state\u0020applicable\u0020to\u0020this\u0020extension\nE.g.\u0020in\u0020case\u0020of\u0020Fluent,\u0020the\u0020state\u0020\u0022SubsiteID1\u0022\u0020does\u0020not\u0020make\u0020sense",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SiteStateInterface.html#method_stateIsApplicable"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SiteStateInterface\u003A\u003AsetDefaultState\u0028\u0029",
            "name": "setDefaultState",
            "summary": "Reset\u0020the\u0020SiteState\u0020to\u0020it\u0027s\u0020default\u0020state",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SiteStateInterface.html#method_setDefaultState"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SiteStateInterface\u003A\u003AcurrentState\u0028\u0029",
            "name": "currentState",
            "summary": "Return\u0020the\u0020current\u0020state\u0020of\u0020the\u0020site",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SiteStateInterface.html#method_currentState"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SiteStateInterface\u003A\u003AactivateState\u0028\u0029",
            "name": "activateState",
            "summary": "Activate\u0020a\u0020given\u0020state.\u0020This\u0020should\u0020only\u0020be\u0020done\u0020if\u0020the\u0020state\u0020is\u0020applicable",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SiteStateInterface.html#method_activateState"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces\\SiteStateInterface\u003A\u003AupdateQuery\u0028\u0029",
            "name": "updateQuery",
            "summary": "Method\u0020to\u0020alter\u0020the\u0020query.\u0020Can\u0020be\u0020no\u002Dop.",
            "url": "classes/Firesphere-SearchBackend-Interfaces-SiteStateInterface.html#method_updateQuery"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass",
            "name": "DirtyClass",
            "summary": "Class\u0020\\Firesphere\\SearchBackend\\Models\\DirtyClass",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003AgetCMSFields\u0028\u0029",
            "name": "getCMSFields",
            "summary": "Make\u0020the\u0020CMS\u0020fields\u0020readable",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#method_getCMSFields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003AcanDelete\u0028\u0029",
            "name": "canDelete",
            "summary": "Nope,\u0020can\u0027t\u0020delete\u0020these",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#method_canDelete"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003AcanEdit\u0028\u0029",
            "name": "canEdit",
            "summary": "Nope,\u0020can\u0027t\u0020edit\u0020these",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#method_canEdit"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003AcanCreate\u0028\u0029",
            "name": "canCreate",
            "summary": "Nope,\u0020can\u0027t\u0020create\u0020these",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#method_canCreate"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#property_table_name"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003A\u0024singular_name",
            "name": "singular_name",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#property_singular_name"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003A\u0024plural_name",
            "name": "plural_name",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#property_plural_name"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\DirtyClass\u003A\u003A\u0024summary_fields",
            "name": "summary_fields",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-DirtyClass.html#property_summary_fields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog",
            "name": "SearchLog",
            "summary": "Class\u0020\\Firesphere\\SearchSearch\\Models\\SearchLog",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003AonBeforeWrite\u0028\u0029",
            "name": "onBeforeWrite",
            "summary": "Convert\u0020the\u0020Timestamp\u0020to\u0020a\u0020DBDatetime\u0020for\u0020compatibility",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#method_onBeforeWrite"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003AgetLastErrorLine\u0028\u0029",
            "name": "getLastErrorLine",
            "summary": "Return\u0020the\u0020first\u0020line\u0020of\u0020this\u0020log\u0020item\u0020error",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#method_getLastErrorLine"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003AcanCreate\u0028\u0029",
            "name": "canCreate",
            "summary": "Not\u0020creatable\u0020by\u0020users",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#method_canCreate"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003AcanEdit\u0028\u0029",
            "name": "canEdit",
            "summary": "Not\u0020editable\u0020by\u0020users",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#method_canEdit"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003AcanView\u0028\u0029",
            "name": "canView",
            "summary": "Member\u0020has\u0020view\u0020access\u003F",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#method_canView"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003AcanDelete\u0028\u0029",
            "name": "canDelete",
            "summary": "Only\u0020deleteable\u0020by\u0020admins\u0020or\u0020when\u0020in\u0020dev\u0020mode\u0020to\u0020clean\u0020up",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#method_canDelete"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003AgetExtraClass\u0028\u0029",
            "name": "getExtraClass",
            "summary": "Get\u0020the\u0020extra\u0020classes\u0020to\u0020colour\u0020the\u0020gridfield\u0020rows",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#method_getExtraClass"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003AprovidePermissions\u0028\u0029",
            "name": "providePermissions",
            "summary": "Return\u0020a\u0020map\u0020of\u0020permission\u0020codes\u0020to\u0020add\u0020to\u0020the\u0020dropdown\u0020shown\u0020in\u0020the\u0020Security\u0020section\u0020of\u0020the\u0020CMS.",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#method_providePermissions"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003A\u0024row_color",
            "name": "row_color",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#property_row_color"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#property_table_name"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003A\u0024summary_fields",
            "name": "summary_fields",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#property_summary_fields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003A\u0024searchable_fields",
            "name": "searchable_fields",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#property_searchable_fields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003A\u0024indexes",
            "name": "indexes",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#property_indexes"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchLog\u003A\u003A\u0024default_sort",
            "name": "default_sort",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchLog.html#property_default_sort"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym",
            "name": "SearchSynonym",
            "summary": "Class\u0020\\Firesphere\\SearchBackend\\Models\\SearchSynonym",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym\u003A\u003AgetCMSFields\u0028\u0029",
            "name": "getCMSFields",
            "summary": "Get\u0020the\u0020required\u0020CMS\u0020Fields\u0020for\u0020this\u0020synonym",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html#method_getCMSFields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym\u003A\u003AgetCombinedSynonym\u0028\u0029",
            "name": "getCombinedSynonym",
            "summary": "Combine\u0020this\u0020synonym\u0020in\u0020to\u0020a\u0020string\u0020for\u0020the\u0020Elastic\u0020synonyms,\u0020or\u0020Solr\u0020synonyms.txt\u0020file",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html#method_getCombinedSynonym"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym\u003A\u003AgetModifiedID\u0028\u0029",
            "name": "getModifiedID",
            "summary": "Get\u0020an\u0020ID\u0020for\u0020usage\u0020as\u0020reference,\u0020e.g.\u0020in\u0020Elastic.",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html#method_getModifiedID"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym\u003A\u003A\u0024table_name",
            "name": "table_name",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html#property_table_name"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym\u003A\u003A\u0024singular_name",
            "name": "singular_name",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html#property_singular_name"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym\u003A\u003A\u0024plural_name",
            "name": "plural_name",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html#property_plural_name"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html#property_db"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models\\SearchSynonym\u003A\u003A\u0024summary_fields",
            "name": "summary_fields",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Models-SearchSynonym.html#property_summary_fields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery",
            "name": "BaseQuery",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AgetTerms\u0028\u0029",
            "name": "getTerms",
            "summary": "Get\u0020the\u0020search\u0020terms",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_getTerms"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AsetTerms\u0028\u0029",
            "name": "setTerms",
            "summary": "Set\u0020the\u0020search\u0020tearms",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_setTerms"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AaddTerm\u0028\u0029",
            "name": "addTerm",
            "summary": "Each\u0020boosted\u0020query\u0020needs\u0020a\u0020separate\u0020addition\u0021\ne.g.\u0020\u0024this\u002D\u003EaddTerm\u0028\u0027test\u0027,\u0020\u005B\u0027MyField\u0027,\u0020\u0027MyOtherField\u0027\u005D,\u00203\u0029\nfollowed\u0020by\n\u0024this\u002D\u003EaddTerm\u0028\u0027otherTest\u0027,\u0020\u005B\u0027Title\u0027\u005D,\u00205\u0029\u003B",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_addTerm"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AaddFilter\u0028\u0029",
            "name": "addFilter",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_addFilter"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AgetFilters\u0028\u0029",
            "name": "getFilters",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_getFilters"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AsetFilters\u0028\u0029",
            "name": "setFilters",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_setFilters"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AgetOrFilters\u0028\u0029",
            "name": "getOrFilters",
            "summary": "Get\u0020the\u0020OR\u0020filters\u0020for\u0020this\u0020query",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_getOrFilters"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AsetOrFilters\u0028\u0029",
            "name": "setOrFilters",
            "summary": "Set\u0020the\u0020or\u0020filters\u0020for\u0020this\u0020query",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_setOrFilters"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AaddOrFilters\u0028\u0029",
            "name": "addOrFilters",
            "summary": "Add\u0020the\u0020or\u0020filters\u0020in\u0020a\u0020key\u002Dvalue\u0020pair",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_addOrFilters"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AgetStart\u0028\u0029",
            "name": "getStart",
            "summary": "Get\u0020the\u0020offset\u0020to\u0020start",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_getStart"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AsetStart\u0028\u0029",
            "name": "setStart",
            "summary": "Set\u0020the\u0020offset\u0020to\u0020start",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_setStart"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AgetRows\u0028\u0029",
            "name": "getRows",
            "summary": "Get\u0020the\u0020rows\u0020to\u0020return",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_getRows"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AsetRows\u0028\u0029",
            "name": "setRows",
            "summary": "Set\u0020the\u0020rows\u0020to\u0020return",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_setRows"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AgetSort\u0028\u0029",
            "name": "getSort",
            "summary": "Get\u0020the\u0020sort\u0020fields",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_getSort"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AsetSort\u0028\u0029",
            "name": "setSort",
            "summary": "Set\u0020the\u0020sort\u0020fields",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_setSort"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AaddSort\u0028\u0029",
            "name": "addSort",
            "summary": "Add\u0020a\u0020sort\u0020field\u0020and\u0020direction",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_addSort"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AgetBoostedFields\u0028\u0029",
            "name": "getBoostedFields",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_getBoostedFields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AsetBoostedFields\u0028\u0029",
            "name": "setBoostedFields",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_setBoostedFields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AaddBoostedField\u0028\u0029",
            "name": "addBoostedField",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_addBoostedField"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AisHighlight\u0028\u0029",
            "name": "isHighlight",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_isHighlight"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003AsetHighlight\u0028\u0029",
            "name": "setHighlight",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#method_setHighlight"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024start",
            "name": "start",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_start"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024rows",
            "name": "rows",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_rows"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024sort",
            "name": "sort",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_sort"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024filters",
            "name": "filters",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_filters"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024orFilters",
            "name": "orFilters",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_orFilters"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024terms",
            "name": "terms",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_terms"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024boostedFields",
            "name": "boostedFields",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_boostedFields"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024highlight",
            "name": "highlight",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_highlight"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries\\BaseQuery\u003A\u003A\u0024spellcheck",
            "name": "spellcheck",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Queries-BaseQuery.html#property_spellcheck"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService",
            "name": "BaseService",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#method___construct"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003AfilterIndexes\u0028\u0029",
            "name": "filterIndexes",
            "summary": "Filter\u0020enabled\u0020indexes\u0020down\u0020to\u0020valid\u0020indexes\u0020that\u0020can\u0020be\u0020instantiated\nor\u0020are\u0020allowed\u0020from\u0020config",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#method_filterIndexes"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003AcheckReflection\u0028\u0029",
            "name": "checkReflection",
            "summary": "Check\u0020if\u0020the\u0020class\u0020is\u0020instantiable",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#method_checkReflection"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003AgetValidIndexes\u0028\u0029",
            "name": "getValidIndexes",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#method_getValidIndexes"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003AsetValidIndexes\u0028\u0029",
            "name": "setValidIndexes",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#method_setValidIndexes"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003AID_FIELD",
            "name": "ID_FIELD",
            "summary": "Unique\u0020ID\u0020in\u0020Search\u0020engine",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#constant_ID_FIELD"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003ACLASS_ID_FIELD",
            "name": "CLASS_ID_FIELD",
            "summary": "SilverStripe\u0020ID\u0020of\u0020the\u0020object",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#constant_CLASS_ID_FIELD"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003ACLASSNAME",
            "name": "CLASSNAME",
            "summary": "Name\u0020of\u0020the\u0020field\u0020that\u0020can\u0020be\u0020used\u0020for\u0020queries",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#constant_CLASSNAME"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003A\u0024baseIndexes",
            "name": "baseIndexes",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#property_baseIndexes"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services\\BaseService\u003A\u003A\u0024validIndexes",
            "name": "validIndexes",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Services-BaseService.html#property_validIndexes"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState",
            "name": "SiteState",
            "summary": "Class\u0020SiteState",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AgetStates\u0028\u0029",
            "name": "getStates",
            "summary": "Get\u0020available\u0020states",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_getStates"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AsetStates\u0028\u0029",
            "name": "setStates",
            "summary": "Set\u0020states",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_setStates"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AaddState\u0028\u0029",
            "name": "addState",
            "summary": "Add\u0020a\u0020state",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_addState"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AaddStates\u0028\u0029",
            "name": "addStates",
            "summary": "Add\u0020multiple\u0020states",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_addStates"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AhasExtension\u0028\u0029",
            "name": "hasExtension",
            "summary": "Does\u0020this\u0020class,\u0020it\u0027s\u0020parent\u0020\u0028or\u0020optionally\u0020one\u0020of\u0020it\u0027s\u0020children\u0029\u0020have\u0020the\u0020passed\u0020extension\u0020attached\u003F",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_hasExtension"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AcurrentStates\u0028\u0029",
            "name": "currentStates",
            "summary": "Get\u0020the\u0020current\u0020state\u0020of\u0020every\u0020variant",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_currentStates"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003A\u0024variants",
            "name": "variants",
            "summary": "Variants\u0020of\u0020SiteState\u0020that\u0020can\u0020be\u0020activated",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#property_variants"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AisApplicable\u0028\u0029",
            "name": "isApplicable",
            "summary": "Is\u0020this\u0020extension\u0020applied\u0020and\u0020instantiable,\u0020and\u0020should\u0020it\u0020be\u0020applied\u0020to\nthe\u0020current\u0020state\u0020of\u0020the\u0020site",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_isApplicable"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AappliesToEnvironment\u0028\u0029",
            "name": "appliesToEnvironment",
            "summary": "Does\u0020this\u0020state\u0020apply\u0020to\u0020the\u0020current\u0020object\/environment\u0020settings",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_appliesToEnvironment"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AisEnabled\u0028\u0029",
            "name": "isEnabled",
            "summary": "Is\u0020this\u0020state\u0020enabled",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_isEnabled"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AsetEnabled\u0028\u0029",
            "name": "setEnabled",
            "summary": "Set\u0020the\u0020state\u0020to\u0020whatever\u0020is\u0020required.\u0020Most\u0020commonly\u0020true",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_setEnabled"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AwithState\u0028\u0029",
            "name": "withState",
            "summary": "Activate\u0020a\u0020site\u0020state\u0020for\u0020indexing",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_withState"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AalterQuery\u0028\u0029",
            "name": "alterQuery",
            "summary": "Alter\u0020the\u0020query\u0020for\u0020each\u0020instance",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_alterQuery"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AgetDefaultStates\u0028\u0029",
            "name": "getDefaultStates",
            "summary": "Get\u0020the\u0020states\u0020set\u0020as\u0020default",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_getDefaultStates"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003AsetDefaultStates\u0028\u0029",
            "name": "setDefaultStates",
            "summary": "Set\u0020the\u0020default\u0020states",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#method_setDefaultStates"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003ADEFAULT_STATE",
            "name": "DEFAULT_STATE",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#constant_DEFAULT_STATE"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003A\u0024states",
            "name": "states",
            "summary": "States\u0020that\u0020can\u0020be\u0020applied",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#property_states"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003A\u0024defaultStates",
            "name": "defaultStates",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#property_defaultStates"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003A\u0024enabled",
            "name": "enabled",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#property_enabled"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States\\SiteState\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-States-SiteState.html#property_state"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IndexingTraits\\IndexingTrait",
            "name": "IndexingTrait",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-IndexingTraits-IndexingTrait.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IndexingTraits\\IndexingTrait\u003A\u003AtaskSetup\u0028\u0029",
            "name": "taskSetup",
            "summary": "Set\u0020up\u0020the\u0020requirements\u0020for\u0020this\u0020task",
            "url": "classes/Firesphere-SearchBackend-Traits-IndexingTraits-IndexingTrait.html#method_taskSetup"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IndexingTraits\\IndexingTrait\u003A\u003AindexClassForIndex\u0028\u0029",
            "name": "indexClassForIndex",
            "summary": "Index\u0020the\u0020classes\u0020for\u0020a\u0020specific\u0020index",
            "url": "classes/Firesphere-SearchBackend-Traits-IndexingTraits-IndexingTrait.html#method_indexClassForIndex"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IndexingTraits\\IndexingTrait\u003A\u003AhasPCNTL\u0028\u0029",
            "name": "hasPCNTL",
            "summary": "Check\u0020if\u0020PCNTL\u0020is\u0020available\u0020and\/or\u0020useable.",
            "url": "classes/Firesphere-SearchBackend-Traits-IndexingTraits-IndexingTrait.html#method_hasPCNTL"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IndexingTraits\\IndexingTrait\u003A\u003AspawnChildren\u0028\u0029",
            "name": "spawnChildren",
            "summary": "For\u0020each\u0020core,\u0020spawn\u0020a\u0020child\u0020process\u0020that\u0020will\u0020handle\u0020a\u0020separate\u0020group.",
            "url": "classes/Firesphere-SearchBackend-Traits-IndexingTraits-IndexingTrait.html#method_spawnChildren"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IndexingTraits\\IndexingTrait\u003A\u003ArunForkedChild\u0028\u0029",
            "name": "runForkedChild",
            "summary": "Create\u0020a\u0020fork\u0020and\u0020run\u0020the\u0020child",
            "url": "classes/Firesphere-SearchBackend-Traits-IndexingTraits-IndexingTrait.html#method_runForkedChild"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait",
            "name": "DataResolveTrait",
            "summary": "Trait\u0020ResolveTrait\u0020All\u0020resolver\u0020methods\u0020for\u0020the\u0020DataResolver",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003AresolveArrayData\u0028\u0029",
            "name": "resolveArrayData",
            "summary": "Resolves\u0020an\u0020ArrayData\u0020value",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#method_resolveArrayData"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003AcannotIdentifyException\u0028\u0029",
            "name": "cannotIdentifyException",
            "summary": "Each\u0020class\u0020using\u0020this\u0020trait\u0020should\u0020have\u0020a\u0020way\u0020to\u0020throw\u0020unidentifiable\u0020objects\u0020or\u0020items",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#method_cannotIdentifyException"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003AresolveList\u0028\u0029",
            "name": "resolveList",
            "summary": "Resolves\u0020a\u0020DataList\u0020values",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#method_resolveList"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003AresolveField\u0028\u0029",
            "name": "resolveField",
            "summary": "Resolves\u0020a\u0020Single\u0020field\u0020in\u0020the\u0020database.",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#method_resolveField"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003AcheckHasMethod\u0028\u0029",
            "name": "checkHasMethod",
            "summary": "Check\u0020if\u0020a\u0020component\u0020has\u0020the\u0020method\u0020instead\u0020of\u0020it\u0020being\u0020a\u0020property",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#method_checkHasMethod"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003AresolveDataObject\u0028\u0029",
            "name": "resolveDataObject",
            "summary": "Resolves\u0020a\u0020DataObject\u0020value",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#method_resolveDataObject"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003AgetMethodValue\u0028\u0029",
            "name": "getMethodValue",
            "summary": "Get\u0020the\u0020value\u0020for\u0020a\u0020method",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#method_getMethodValue"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003AgetFieldValue\u0028\u0029",
            "name": "getFieldValue",
            "summary": "Get\u0020the\u0020value\u0020for\u0020a\u0020field",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#method_getFieldValue"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003A\u0024component",
            "name": "component",
            "summary": "Component\u0020to\u0020resolve",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#property_component"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003A\u0024columns",
            "name": "columns",
            "summary": "Columns\u0020to\u0020resolve",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#property_columns"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003A\u0024columnName",
            "name": "columnName",
            "summary": "Column\u0020to\u0020resolve",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#property_columnName"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\DataResolveTrait\u003A\u003A\u0024shortName",
            "name": "shortName",
            "summary": "ShortName\u0020of\u0020a\u0020class",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-DataResolveTrait.html#property_shortName"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\GetSetSearchResolverTrait",
            "name": "GetSetSearchResolverTrait",
            "summary": "Setters\u0020and\u0020getters\u0020for\u0020the\u0020introspection.",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-GetSetSearchResolverTrait.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\GetSetSearchResolverTrait\u003A\u003AgetIndex\u0028\u0029",
            "name": "getIndex",
            "summary": "Get\u0020the\u0020current\u0020index",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-GetSetSearchResolverTrait.html#method_getIndex"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\GetSetSearchResolverTrait\u003A\u003AsetIndex\u0028\u0029",
            "name": "setIndex",
            "summary": "Set\u0020the\u0020current\u0020index",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-GetSetSearchResolverTrait.html#method_setIndex"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits\\GetSetSearchResolverTrait\u003A\u003A\u0024index",
            "name": "index",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-IntrospectionTraits-GetSetSearchResolverTrait.html#property_index"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\LoggerTrait",
            "name": "LoggerTrait",
            "summary": "Trait\u0020LoggerTrait",
            "url": "classes/Firesphere-SearchBackend-Traits-LoggerTrait.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\LoggerTrait\u003A\u003AgetLogger\u0028\u0029",
            "name": "getLogger",
            "summary": "Get\u0020the\u0020logger",
            "url": "classes/Firesphere-SearchBackend-Traits-LoggerTrait.html#method_getLogger"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\LoggerTrait\u003A\u003AsetLogger\u0028\u0029",
            "name": "setLogger",
            "summary": "Set\u0020the\u0020logger\u0020if\u0020needed",
            "url": "classes/Firesphere-SearchBackend-Traits-LoggerTrait.html#method_setLogger"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\LoggerTrait\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "The\u0020logger\u0020to\u0020use",
            "url": "classes/Firesphere-SearchBackend-Traits-LoggerTrait.html#property_logger"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\QueryTraits\\QueryFilterTrait",
            "name": "QueryFilterTrait",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-QueryTraits-QueryFilterTrait.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\QueryTraits\\QueryFilterTrait\u003A\u003AgetViewStatusFilter\u0028\u0029",
            "name": "getViewStatusFilter",
            "summary": "Add\u0020filtering\u0020on\u0020view\u0020status",
            "url": "classes/Firesphere-SearchBackend-Traits-QueryTraits-QueryFilterTrait.html#method_getViewStatusFilter"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait",
            "name": "SearchResultGetTrait",
            "summary": "Trait\u0020SearchResultGetTrait",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait\u003A\u003AgetFacets\u0028\u0029",
            "name": "getFacets",
            "summary": "Retrieve\u0020the\u0020facets\u0020from\u0020the\u0020results",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html#method_getFacets"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait\u003A\u003AgetHighlight\u0028\u0029",
            "name": "getHighlight",
            "summary": "Get\u0020the\u0020highlighting",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html#method_getHighlight"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait\u003A\u003AgetSpellcheck\u0028\u0029",
            "name": "getSpellcheck",
            "summary": "Get\u0020the\u0020spellchecked\u0020results",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html#method_getSpellcheck"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait\u003A\u003AgetTotalItems\u0028\u0029",
            "name": "getTotalItems",
            "summary": "Total\u0020items\u0020in\u0020the\u0020result",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html#method_getTotalItems"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait\u003A\u003A\u0024totalItems",
            "name": "totalItems",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html#property_totalItems"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait\u003A\u003A\u0024facets",
            "name": "facets",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html#property_facets"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait\u003A\u003A\u0024highlight",
            "name": "highlight",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html#property_highlight"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultGetTrait\u003A\u003A\u0024spellcheck",
            "name": "spellcheck",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultGetTrait.html#property_spellcheck"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultSetTrait",
            "name": "SearchResultSetTrait",
            "summary": "Trait\u0020SearchResultSetTrait",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultSetTrait.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultSetTrait\u003A\u003AsetHighlight\u0028\u0029",
            "name": "setHighlight",
            "summary": "Set\u0020the\u0020highlighted\u0020items",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultSetTrait.html#method_setHighlight"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultSetTrait\u003A\u003AsetTotalItems\u0028\u0029",
            "name": "setTotalItems",
            "summary": "Set\u0020the\u0020total\u0020amount\u0020of\u0020results",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultSetTrait.html#method_setTotalItems"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultSetTrait\u003A\u003AsetFacets\u0028\u0029",
            "name": "setFacets",
            "summary": "Set\u0020the\u0020facets\u0020to\u0020build",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultSetTrait.html#method_setFacets"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultSetTrait\u003A\u003AbuildFacets\u0028\u0029",
            "name": "buildFacets",
            "summary": "Build\u0020the\u0020given\u0020list\u0020of\u0020key\u002Dvalue\u0020pairs\u0020in\u0020to\u0020a\u0020SilverStripe\u0020useable\u0020array",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultSetTrait.html#method_buildFacets"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultSetTrait\u003A\u003A\u0024totalItems",
            "name": "totalItems",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultSetTrait.html#property_totalItems"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultSetTrait\u003A\u003A\u0024facets",
            "name": "facets",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultSetTrait.html#property_facets"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\SearchResultSetTrait\u003A\u003A\u0024highlight",
            "name": "highlight",
            "summary": "",
            "url": "classes/Firesphere-SearchBackend-Traits-SearchResultSetTrait.html#property_highlight"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Admins",
            "name": "Admins",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-admins.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend",
            "name": "SearchBackend",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend.html"
        },                {
            "fqsen": "\\Firesphere",
            "name": "Firesphere",
            "summary": "",
            "url": "namespaces/firesphere.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Extensions",
            "name": "Extensions",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-extensions.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-factories.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-helpers.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Indexes",
            "name": "Indexes",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-indexes.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-interfaces.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-models.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Queries",
            "name": "Queries",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-queries.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-services.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\States",
            "name": "States",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-states.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IndexingTraits",
            "name": "IndexingTraits",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-traits-indexingtraits.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\IntrospectionTraits",
            "name": "IntrospectionTraits",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-traits-introspectiontraits.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-traits.html"
        },                {
            "fqsen": "\\Firesphere\\SearchBackend\\Traits\\QueryTraits",
            "name": "QueryTraits",
            "summary": "",
            "url": "namespaces/firesphere-searchbackend-traits-querytraits.html"
        }            ]
);
