Search.appendIndex(
    [
                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator",
            "name": "DataObjectAnnotator",
            "summary": "Class\u0020DataObjectAnnotator\nGenerates\u0020phpdoc\u0020annotations\u0020for\u0020database\u0020fields\u0020and\u0020orm\u0020relations\nso\u0020IDE\u0027s\u0020with\u0020autocompletion\u0020and\u0020property\u0020inspection\u0020will\u0020recognize\u0020properties\nand\u0020relation\u0020methods.",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DataObjectAnnotator\u0020constructor.",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method___construct"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AsetupExtensionClasses\u0028\u0029",
            "name": "setupExtensionClasses",
            "summary": "Named\u0020\u0060setup\u0060\u0020to\u0020not\u0020clash\u0020with\u0020the\u0020actual\u0020setter",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_setupExtensionClasses"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AsetEnabledClasses\u0028\u0029",
            "name": "setEnabledClasses",
            "summary": "Get\u0020all\u0020annotatable\u0020classes\u0020from\u0020enabled\u0020modules",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_setEnabledClasses"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AgetExtensionClasses\u0028\u0029",
            "name": "getExtensionClasses",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_getExtensionClasses"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AsetExtensionClasses\u0028\u0029",
            "name": "setExtensionClasses",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_setExtensionClasses"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003ApushExtensionClass\u0028\u0029",
            "name": "pushExtensionClass",
            "summary": "Add\u0020another\u0020extension\u0020class\nFalse\u0020checking,\u0020because\u0020what\u0020we\u0020get\u0020might\u0020be\u0020uppercase\u0020and\u0020then\u0020lowercase\nAllowing\u0020for\u0020duplicates\u0020here,\u0020to\u0020clean\u0020up\u0020later",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_pushExtensionClass"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AisEnabled\u0028\u0029",
            "name": "isEnabled",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_isEnabled"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AannotateModule\u0028\u0029",
            "name": "annotateModule",
            "summary": "Generate\u0020docblock\u0020for\u0020all\u0020subclasses\u0020of\u0020DataObjects\u0020and\u0020DataExtenions\nwithin\u0020a\u0020module.",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_annotateModule"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AgetClassesForModule\u0028\u0029",
            "name": "getClassesForModule",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_getClassesForModule"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AannotateObject\u0028\u0029",
            "name": "annotateObject",
            "summary": "Generate\u0020docblock\u0020for\u0020a\u0020single\u0020subclass\u0020of\u0020DataObject\u0020or\u0020DataExtenions",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_annotateObject"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AwriteFileContent\u0028\u0029",
            "name": "writeFileContent",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_writeFileContent"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003AgetGeneratedFileContent\u0028\u0029",
            "name": "getGeneratedFileContent",
            "summary": "Return\u0020the\u0020complete\u0020File\u0020content\u0020with\u0020the\u0020newly\u0020generated\u0020DocBlocks",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#method_getGeneratedFileContent"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003A\u0024extension_classes",
            "name": "extension_classes",
            "summary": "All\u0020classes\u0020that\u0020subclass\u0020Object",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#property_extension_classes"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003A\u0024enabled",
            "name": "enabled",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#property_enabled"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003A\u0024enabled_modules",
            "name": "enabled_modules",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#property_enabled_modules"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003A\u0024permissionChecker",
            "name": "permissionChecker",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#property_permissionChecker"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003A\u0024annotatableClasses",
            "name": "annotatableClasses",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#property_annotatableClasses"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\DataObjectAnnotator\u003A\u003A\u0024dbfield_tagnames",
            "name": "dbfield_tagnames",
            "summary": "Default\u0020tagname\u0020will\u0020be\u0020\u0040string\u0020.",
            "url": "classes/SilverLeague-IDEAnnotator-DataObjectAnnotator.html#property_dbfield_tagnames"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable",
            "name": "Annotatable",
            "summary": "Class\u0020Annotatable",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003AafterCallActionHandler\u0028\u0029",
            "name": "afterCallActionHandler",
            "summary": "Annotated\u0020Controllers\u0020and\u0020Extensions",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#method_afterCallActionHandler"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003AannotateModules\u0028\u0029",
            "name": "annotateModules",
            "summary": "Conditionally\u0020annotate\u0020this\u0020project\u0027s\u0020modules\u0020if\u0020enabled\u0020and\u0020not\u0020skipped",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#method_annotateModules"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003AsetUp\u0028\u0029",
            "name": "setUp",
            "summary": "Annotatable\u0020setup.",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#method_setUp"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003AdisplayMessage\u0028\u0029",
            "name": "displayMessage",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#method_displayMessage"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003AgetAnnotator\u0028\u0029",
            "name": "getAnnotator",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#method_getAnnotator"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003AgetPermissionChecker\u0028\u0029",
            "name": "getPermissionChecker",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#method_getPermissionChecker"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003A\u0024annotated_extensions",
            "name": "annotated_extensions",
            "summary": "Keep\u0020track\u0020ot\u0020the\u0020annotation\u0020actions\u0020for\u0020extensions\nAn\u0020Extension\u0020can\u0020belong\u0020to\u0020many\u0020DataObjects.",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#property_annotated_extensions"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003A\u0024annotator",
            "name": "annotator",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#property_annotator"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions\\Annotatable\u003A\u003A\u0024permissionChecker",
            "name": "permissionChecker",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Extensions-Annotatable.html#property_permissionChecker"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator",
            "name": "AbstractTagGenerator",
            "summary": "AbstractTagGenerator",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DocBlockTagGenerator\u0020constructor.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method___construct"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgetSupportedTagTypes\u0028\u0029",
            "name": "getSupportedTagTypes",
            "summary": "List\u0020of\u0020supported\u0020tags.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_getSupportedTagTypes"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgenerateTags\u0028\u0029",
            "name": "generateTags",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_generateTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgetTags\u0028\u0029",
            "name": "getTags",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_getTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgenerateExtensionsTags\u0028\u0029",
            "name": "generateExtensionsTags",
            "summary": "Generate\u0020the\u0020mixins\u0020for\u0020DataExtensions.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_generateExtensionsTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgetClassConfig\u0028\u0029",
            "name": "getClassConfig",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_getClassConfig"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgetAnnotationClassName\u0028\u0029",
            "name": "getAnnotationClassName",
            "summary": "Check\u0020if\u0020we\u0020need\u0020to\u0020use\u0020the\u0020short\u0020name\u0020for\u0020a\u0020class",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_getAnnotationClassName"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003ApushMixinTag\u0028\u0029",
            "name": "pushMixinTag",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_pushMixinTag"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003ApushTagWithExistingComment\u0028\u0029",
            "name": "pushTagWithExistingComment",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_pushTagWithExistingComment"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgetExistingTagCommentByTagString\u0028\u0029",
            "name": "getExistingTagCommentByTagString",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_getExistingTagCommentByTagString"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgetExistingTags\u0028\u0029",
            "name": "getExistingTags",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_getExistingTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgenerateOwnerTags\u0028\u0029",
            "name": "generateOwnerTags",
            "summary": "Generate\u0020the\u0020Owner\u002Dproperties\u0020for\u0020extensions.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_generateOwnerTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003AgetOwnerClasses\u0028\u0029",
            "name": "getOwnerClasses",
            "summary": "Get\u0020all\u0020owner\u0020classes\u0020of\u0020the\u0020given\u0020extension\u0020class",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_getOwnerClasses"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003ApushPropertyTag\u0028\u0029",
            "name": "pushPropertyTag",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_pushPropertyTag"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003ApushMethodTag\u0028\u0029",
            "name": "pushMethodTag",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#method_pushMethodTag"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003A\u0024className",
            "name": "className",
            "summary": "The\u0020current\u0020class\u0020we\u0020are\u0020working\u0020with",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#property_className"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003A\u0024existingTags",
            "name": "existingTags",
            "summary": "The\u0020existing\u0020tags\u0020of\u0020the\u0020class\u0020we\u0020are\u0020working\u0020with",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#property_existingTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003A\u0024reflector",
            "name": "reflector",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#property_reflector"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003A\u0024tags",
            "name": "tags",
            "summary": "List\u0020all\u0020the\u0020generated\u0020tags\u0020form\u0020the\u0020various\u0020generateSomeORMProperies\u0020methods",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#property_tags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003A\u0024tagFactory",
            "name": "tagFactory",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#property_tagFactory"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\AbstractTagGenerator\u003A\u003A\u0024pageClassesCache",
            "name": "pageClassesCache",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-AbstractTagGenerator.html#property_pageClassesCache"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\ControllerTagGenerator",
            "name": "ControllerTagGenerator",
            "summary": "AbstractTagGenerator",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-ControllerTagGenerator.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\ControllerTagGenerator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "ControllerTagGenerator\u0020constructor.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-ControllerTagGenerator.html#method___construct"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\ControllerTagGenerator\u003A\u003AgenerateTags\u0028\u0029",
            "name": "generateTags",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-ControllerTagGenerator.html#method_generateTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\ControllerTagGenerator\u003A\u003AgenerateControllerObjectTags\u0028\u0029",
            "name": "generateControllerObjectTags",
            "summary": "Generate\u0020the\u0020controller\u0020tags,\u0020these\u0020differ\u0020slightly\u0020from\u0020the\u0020standard\u0020ORM\u0020tags",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-ControllerTagGenerator.html#method_generateControllerObjectTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\ControllerTagGenerator\u003A\u003AisContentController\u0028\u0029",
            "name": "isContentController",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-ControllerTagGenerator.html#method_isContentController"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\ControllerTagGenerator\u003A\u003AmapPageTypesToControllerName\u0028\u0029",
            "name": "mapPageTypesToControllerName",
            "summary": "Generates\u0020the\u0020cache\u0020of\u0020Page\u0020types\u0020to\u0020Controllers\u0020when\u0020the\u0020controller_name\u0020config\u0020is\u0020used",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-ControllerTagGenerator.html#method_mapPageTypesToControllerName"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator",
            "name": "DocBlockGenerator",
            "summary": "Class\u0020DocBlockGenerator",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DocBlockGenerator\u0020constructor.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#method___construct"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003AgetExistingTags\u0028\u0029",
            "name": "getExistingTags",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#method_getExistingTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003AgetExistingDocBlock\u0028\u0029",
            "name": "getExistingDocBlock",
            "summary": "Not\u0020that\u0020in\u0020case\u0020there\u0020are\u0020multiple\u0020doblocks\u0020for\u0020a\u0020class,\nthe\u0020last\u0020one\u0020will\u0020be\u0020returned",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#method_getExistingDocBlock"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003AgetGeneratedDocBlock\u0028\u0029",
            "name": "getGeneratedDocBlock",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#method_getGeneratedDocBlock"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003AmergeGeneratedTagsIntoDocBlock\u0028\u0029",
            "name": "mergeGeneratedTagsIntoDocBlock",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#method_mergeGeneratedTagsIntoDocBlock"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003AremoveExistingSupportedTags\u0028\u0029",
            "name": "removeExistingSupportedTags",
            "summary": "Remove\u0020all\u0020existing\u0020tags\u0020that\u0020are\u0020supported\u0020by\u0020this\u0020module.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#method_removeExistingSupportedTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003AgetGeneratedTags\u0028\u0029",
            "name": "getGeneratedTags",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#method_getGeneratedTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003A\u0024className",
            "name": "className",
            "summary": "The\u0020current\u0020class\u0020we\u0020are\u0020working\u0020with",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#property_className"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003A\u0024reflector",
            "name": "reflector",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#property_reflector"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003A\u0024tagGenerator",
            "name": "tagGenerator",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#property_tagGenerator"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\DocBlockGenerator\u003A\u003A\u0024docBlockFactory",
            "name": "docBlockFactory",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-DocBlockGenerator.html#property_docBlockFactory"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator",
            "name": "OrmTagGenerator",
            "summary": "OrmTagGenerator\nThis\u0020class\u0020generates\u0020DocBlock\u0020Tags\u0020for\u0020the\u0020ORM\u0020properties\u0020of\u0020a\u0020Dataobject\u0020of\u0020DataExtension\nand\u0020adds\u0020\u0024owner\u0020Tags\u0020for\u0020added\u0020DataExtensions",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgenerateTags\u0028\u0029",
            "name": "generateTags",
            "summary": "Generates\u0020all\u0020ORM\u0020Tags",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_generateTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgenerateDBTags\u0028\u0029",
            "name": "generateDBTags",
            "summary": "Generate\u0020the\u0020\u0024db\u0020property\u0020values.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_generateDBTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgetTagNameForDBField\u0028\u0029",
            "name": "getTagNameForDBField",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_getTagNameForDBField"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgenerateBelongsToTags\u0028\u0029",
            "name": "generateBelongsToTags",
            "summary": "Generate\u0020the\u0020\u0024belongs_to\u0020property\u0020values.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_generateBelongsToTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AresolveDotNotation\u0028\u0029",
            "name": "resolveDotNotation",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_resolveDotNotation"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgenerateHasOneTags\u0028\u0029",
            "name": "generateHasOneTags",
            "summary": "Generate\u0020the\u0020\u0024has_one\u0020property\u0020and\u0020method\u0020values.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_generateHasOneTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgenerateHasManyTags\u0028\u0029",
            "name": "generateHasManyTags",
            "summary": "Generate\u0020the\u0020\u0024has_many\u0020method\u0020values.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_generateHasManyTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgenerateTagsForDataLists\u0028\u0029",
            "name": "generateTagsForDataLists",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_generateTagsForDataLists"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgenerateManyManyTags\u0028\u0029",
            "name": "generateManyManyTags",
            "summary": "Generate\u0020the\u0020\u0024many_many\u0020method\u0020values.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_generateManyManyTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003AgenerateBelongsManyManyTags\u0028\u0029",
            "name": "generateBelongsManyManyTags",
            "summary": "Generate\u0020the\u0020\u0024belongs_many_many\u0020method\u0020values.",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#method_generateBelongsManyManyTags"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators\\OrmTagGenerator\u003A\u003A\u0024propertyTypes",
            "name": "propertyTypes",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Generators-OrmTagGenerator.html#property_propertyTypes"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotateClassInfo",
            "name": "AnnotateClassInfo",
            "summary": "Class\u0020AnnotateClassInfo\nWe\u0020will\u0020need\u0020this\u0020for\u0020phpDocumentor\u0020as\u0020well.",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotateClassInfo.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotateClassInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "AnnotateClassInfo\u0020constructor.",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotateClassInfo.html#method___construct"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotateClassInfo\u003A\u003AgetModuleName\u0028\u0029",
            "name": "getModuleName",
            "summary": "Where\u0020module\u0020name\u0020is\u0020a\u0020folder\u0020in\u0020the\u0020webroot.",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotateClassInfo.html#method_getModuleName"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotateClassInfo\u003A\u003AgetClassFilePath\u0028\u0029",
            "name": "getClassFilePath",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotateClassInfo.html#method_getClassFilePath"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotateClassInfo\u003A\u003A\u0024className",
            "name": "className",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotateClassInfo.html#property_className"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotateClassInfo\u003A\u003A\u0024reflector",
            "name": "reflector",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotateClassInfo.html#property_reflector"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker",
            "name": "AnnotatePermissionChecker",
            "summary": "Class\u0020AnnotatePermissionChecker",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker\u003A\u003AenvironmentIsAllowed\u0028\u0029",
            "name": "environmentIsAllowed",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html#method_environmentIsAllowed"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker\u003A\u003AisEnabled\u0028\u0029",
            "name": "isEnabled",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html#method_isEnabled"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker\u003A\u003AgetSupportedParentClasses\u0028\u0029",
            "name": "getSupportedParentClasses",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html#method_getSupportedParentClasses"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker\u003A\u003AclassNameIsAllowed\u0028\u0029",
            "name": "classNameIsAllowed",
            "summary": "Check\u0020if\u0020a\u0020DataObject\u0020or\u0020DataExtension\u0020subclass\u0020is\u0020allowed\u0020by\u0020checking\u0020if\u0020the\u0020file\nis\u0020in\u0020the\u0020\u0024allowed_modules\u0020array\nThe\u0020permission\u0020is\u0020checked\u0020by\u0020matching\u0020the\u0020filePath\u0020and\u0020modulePath",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html#method_classNameIsAllowed"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker\u003A\u003AclassNameIsSupported\u0028\u0029",
            "name": "classNameIsSupported",
            "summary": "Check\u0020if\u0020a\u0020\u0028subclass\u0020of\u0020\u0029\u0020class\u0020is\u0020a\u0020supported",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html#method_classNameIsSupported"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker\u003A\u003AmoduleIsAllowed\u0028\u0029",
            "name": "moduleIsAllowed",
            "summary": "Check\u0020if\u0020a\u0020module\u0020is\u0020in\u0020the\u0020\u0024allowed_modules\u0020array\nRequired\u0020for\u0020the\u0020buildTask.",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html#method_moduleIsAllowed"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker\u003A\u003AenabledModules\u0028\u0029",
            "name": "enabledModules",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html#method_enabledModules"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers\\AnnotatePermissionChecker\u003A\u003A\u0024supportedParentClasses",
            "name": "supportedParentClasses",
            "summary": "In\u0020the\u0020future\u0020we\u0020will\u0020support\u0020other\u0020Classes\u0020as\u0020well.",
            "url": "classes/SilverLeague-IDEAnnotator-Helpers-AnnotatePermissionChecker.html#property_supportedParentClasses"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Reflection\\ShortNameResolver",
            "name": "ShortNameResolver",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Reflection-ShortNameResolver.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Reflection\\ShortNameResolver\u003A\u003Aresolve\u0028\u0029",
            "name": "resolve",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Reflection-ShortNameResolver.html#method_resolve"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Tasks\\DataObjectAnnotatorTask",
            "name": "DataObjectAnnotatorTask",
            "summary": "Class\u0020DataObjectAnnotatorTask",
            "url": "classes/SilverLeague-IDEAnnotator-Tasks-DataObjectAnnotatorTask.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Tasks\\DataObjectAnnotatorTask\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "DataObjectAnnotatorTask\u0020constructor.",
            "url": "classes/SilverLeague-IDEAnnotator-Tasks-DataObjectAnnotatorTask.html#method___construct"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Tasks\\DataObjectAnnotatorTask\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/SilverLeague-IDEAnnotator-Tasks-DataObjectAnnotatorTask.html#method_run"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator",
            "name": "IDEAnnotator",
            "summary": "",
            "url": "namespaces/silverleague-ideannotator.html"
        },                {
            "fqsen": "\\SilverLeague",
            "name": "SilverLeague",
            "summary": "",
            "url": "namespaces/silverleague.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Extensions",
            "name": "Extensions",
            "summary": "",
            "url": "namespaces/silverleague-ideannotator-extensions.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Generators",
            "name": "Generators",
            "summary": "",
            "url": "namespaces/silverleague-ideannotator-generators.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/silverleague-ideannotator-helpers.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Reflection",
            "name": "Reflection",
            "summary": "",
            "url": "namespaces/silverleague-ideannotator-reflection.html"
        },                {
            "fqsen": "\\SilverLeague\\IDEAnnotator\\Tasks",
            "name": "Tasks",
            "summary": "",
            "url": "namespaces/silverleague-ideannotator-tasks.html"
        }            ]
);
